### ISSUE TITLE
ERROR .ENV

### ISSUE THREAD

**Issue by juanxodj** [giansalex/lycet#1]
Al ejecutar el comando: composer install --no-dev -o, me instala las dependencias pero con el siguiente error:

Generating optimized autoload files
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught RuntimeException: APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file. in D:\FACTURACIÓN ELECTRÓNICA\lycet\bin\console:20
!!  Stack trace:
!!  #0 {main}
!!    thrown in D:\FACTURACIÓN ELECTRÓNICA\lycet\bin\console on line 20

Y al ejecutar el servidor PHP me lanza este:

Fatal error: Uncaught RuntimeException: APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file. in D:\FACTURACION ELECTRÓNICA\lycet\public\index.php:13 Stack trace: #0 {main} thrown in D:\FACTURACION ELECTRÓNICA\lycet\public\index.php on line 13

He configurado el .env como lo indican. Supongo que es porque no existe este archivo ni esta ruta...
WKHTMLTOPDF_PATH=full/path/wkhtmltopdf.exe

¿Será ese el error?

**Comment by giansalex** [comment]
El problema es que `.env` solo se crea en entorno de desarrollo. Ejecuta:
`composer install -o`

**Comment by giansalex** [comment]
Se abre este issue, porque existe la posibilidad de usar dotenv, para leer las variables de entorno desde `.env`, 
> definir las variables de entorno antes de ejecutar `composer install --no-dev` seria lo ideal, pero en un hosting generalmente no se tiene esa opcion.
