### ISSUE TITLE
Agregar librería webmaster/dompdf-greenter en Lycet

### ISSUE THREAD

**Issue by ajahuanex** [giansalex/lycet#103]
Hola @giansalex, estoy probando la integración de una pequeña librería ´para utilizar  `dompdf` para el renderizado de los documentos pdf en `Lycet `. [webmaster/dompdf-greenter](https://github.com/ajahuanex/dompdf-greenter).

Mi duda es. Si de alguna manera se pudiera editar automáticamente `services.yaml ` en el momento de la instalación de mi librería webmaster/dompdf-greenter . Tal como se muestra en la siguiente figura.
![Screenshot_30](https://user-images.githubusercontent.com/2767765/59180077-94548d80-8b29-11e9-880b-aea831b72d3e.png)

Aún me faltan detalles de configuraciones avanzadas del `dompdf` , pero ya lo probé y me esta funcionando tanto localmente, así como, en un host remoto.

**Comment by giansalex** [comment]
Hola @ajahuanex, entonces lograste obtener un PDF que se logre visualizar correctamente con dompdf?
De acuerdo  tu pregunta, creo que podrías realizarse con un Symfony bundle

**Comment by WEBMA5TER** [comment]
`Dompdf`  si me muestra correctamente el pdf, siempre y cuando la factura tenga una sola hoja. Para más de una hoja, se nesesita modificar la plantilla en el html generado, para que tenga puntos `page-break-before` con css

**Comment by giansalex** [comment]
@WEBMA5TER , cuando dices que se muestra correctamente el pdf, te refieres a las plantillas por defecto que usa greenter, u otras creadas por ti, ya que creo que `dompdf` no soporta características de html, css mas actuales.

**Comment by ajahuanex** [comment]
> @WEBMA5TER , cuando dices que se muestra correctamente el pdf, te refieres a las plantillas por defecto que usa greenter, u otras creadas por ti, ya que creo que `dompdf` no soporta características de html, css mas actuales.

Hola @giansalex  es mi otra cuenta @WEBMA5TER.... 
Bueno, me refería a las plantillas por defecto de `greenter`,  Estuve haciendo pruebas el porque falla cuando el contenido sobrepasa una pagina.
Y llegue a la conclusión de que nó está leendo la media query `
@media print {
  ...
}
` 
del CSS que tiene greenter, y por ese motivo no hace el salto de página en  `
tr {
        page-break-inside: avoid
    }
    *
`   A pesar de que en la documentación si tiene soporte para     
[@media print](https://github.com/dompdf/dompdf/blob/d30679a47a067a69540c988405cb675404898acc/src/Options.php#L69-L81)

**Comment by giansalex** [comment]
Ah me referia al aspecto que tiene el PDF de salida, la ultima vez que subiste un imagen del resultado no parecia aceptable.

**Comment by ajahuanex** [comment]
Era con la librería `mpdf` no soportaba algunas propiedades CSSs, Pero con `dompdf` funcionan al 99% en plantillas de `greenter`

**Comment by giansalex** [comment]
Ejecute el ejemplo que esta en su pagina, y si el resultado es aceptable. Pero el tuyo se muestra mejor, modificaste la plantilla o configuraste otras opciones del `dompdf`?

Si ese es el resultado, estaré pensando a colocar por defecto `dompdf` en vez de `wkhtmltopdf`

**Comment by ajahuanex** [comment]
Si en este momento estoy jugando con algunas opciones de dompdf.
![Screenshot_32](https://user-images.githubusercontent.com/2767765/59233588-bc3a0480-8bae-11e9-861c-c4f04fb30fe0.png)

**Comment by ajahuanex** [comment]
Aquí están las [opciones](https://github.com/dompdf/dompdf/blob/master/src/Options.php) de `dompdf`

**Comment by giansalex** [comment]
Si he visto las opciones, pero mas necesario era que valores poner, llegue a probar cambiando el renderizador a `PFDLib` , que segun decia da un mejor performance, pero es de pago.

**Comment by giansalex** [comment]
La opcion que hace la diferencia es `dpi`, pero en mi caso con valor 135 genera una segunda hoja en blanco (tal vez sea la fuente), tuve que colocar 136.
Tambien en mi editor, marcaba como depreciado el `set_option`, puedes usar la nueva forma:
```php
$options = new \Dompdf\Options();

$options->setDpi(135);
$options->setDefaultPaperSize('A4');
$options->setIsHtml5ParserEnabled(true);
$options->setDefaultMediaType('all');
$options->setIsFontSubsettingEnabled(true);

$dompdf = new Dompdf($options);
```

**Comment by ajahuanex** [comment]
Con 3 items en los detalles de producto me da con `pdi =96` 
![Screenshot_33](https://user-images.githubusercontent.com/2767765/59236631-bf3bf180-8bbc-11e9-8150-ecc4695f67d2.png)

**Comment by ajahuanex** [comment]
El problema de la hoja en blanco se puede solucionar agregando en el css `page-break-inside: avoid` dentro de `table { ....}` ya que Dompdf no reconoce al `tr {...}*`
![Screenshot_34](https://user-images.githubusercontent.com/2767765/59236915-bc8dcc00-8bbd-11e9-9e68-fcca6c4febf2.png)

**Comment by giansalex** [comment]
Si es algo que no afecta al pdf generado por `wkhtmltopdf`, puede agregarse ese codigo al repositorio.

**Comment by ajahuanex** [comment]
Según mis pruebas, he observado que **wkhtmltopdf**, esta usando las propiedades de `@media print{...}` en la hoja de estilos de la plantilla de` Lycet`
![Screenshot_4](https://user-images.githubusercontent.com/2767765/59360774-59538500-8cf6-11e9-8100-7026ec51bb36.png)

**Comment by giansalex** [comment]
si, eso hace.

**Comment by ajahuanex** [comment]
Sin embargo, la gran ventaja de WKHTMLTOPDF, realiza los saltos de pagina, independientemente del `css` es por eso que para DOMPDF sugiero la adicion de 1 linea del css [page-break-inside]( https://github.com/ajahuanex/dompdf-greenter/blob/2b7617787ccede40a952274464798b70db91c987/assets/style.css#L90  ) y comentar algunas propiedades que no afectarian a wkhtmltopdf

**Comment by ajahuanex** [comment]
Esta es la configuración que estoy usando en DOMPDF.
![Screenshot_2](https://user-images.githubusercontent.com/2767765/59361719-e9de9500-8cf7-11e9-9833-75513edc9ec4.png)

**Comment by ajahuanex** [comment]
> si, eso hace.

Quice decir **no** esta usando `@media print{ ...}` por eso es que no esta en negrita algunos textos :)

**Comment by giansalex** [comment]
Si no afecta a `wkhtmltopdf`, se podria aplicar

**Comment by giansalex** [comment]
@ajahuanex al igual que dompdf, `wkthmltopdf` tambien tiene la opción para usar mediatype `print`, por defecto usa `screen`

![image](https://user-images.githubusercontent.com/14926587/59557763-eb35e900-8fa7-11e9-8fbe-c08fbba83326.png)

**Comment by giansalex** [comment]
Se configuro media print en este repositorio, en la confirmación https://github.com/giansalex/lycet/commit/36db8826764363e5822920df2c6f28ed6098fbee

**Comment by giansalex** [comment]
Se configuro media print en este repositorio, en la confirmación https://github.com/giansalex/lycet/commit/36db8826764363e5822920df2c6f28ed6098fbee

**Comment by ajahuanex** [comment]
> @ajahuanex al igual que dompdf, `wkthmltopdf` tambien tiene la opción para usar mediatype `print`, por defecto usa `screen`
> 
> ![image](https://user-images.githubusercontent.com/14926587/59557763-eb35e900-8fa7-11e9-8fbe-c08fbba83326.png)

Se ve mejor en modo `print`. Por mi parte sigo usando `Dompdf` ya que estoy probando en un hosting remoto y modifique algunas lineas del [css](https://github.com/ajahuanex/dompdf-greenter/blob/master/assets/style.css) para que me renderize de la mejor manera. y por supuesto, estos cambios no afecta a WKHTMLTOPDF.
