### ISSUE TITLE
Añadir información extra al PDF

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#105]
Como podría hacer para enviar otros parametros para agregar en la plantilla del PDF, tales como una fecha de vencimiento, si es credito o contado, y demas información, muchas gracias

**Comment by giansalex** [comment]
Hola @OD-n, actualmente no se cuenta con esa opción 😞

**Comment by giansalex** [comment]
Se puede agregar un parámetro adicional para enviar esa informacion, en el endpoint del pdf

**Comment by OD-n** [comment]
Voy a revisar, muchas gracias

**Comment by OD-n** [comment]
Disculpa @giansalex , queria consultar como podría recibir los parametros que envio, si tengo entendido bien, por la url de CURL. 
![Anotación 2019-08-08 203558](https://user-images.githubusercontent.com/28074529/62747920-2d196380-ba1c-11e9-928f-36d2959d0c5f.png)

Estuve siguiendo el metodo `getParameter($key)`; no pude entenderlo muy bien, pude resolver este problema de enviar información extra de otra forma pero no me convencía. Espero puedas ayudarme con ello, gracias.

**Comment by giansalex** [comment]
podría cambiarse en la accion del pdf para que reciba otra entidad, por ejemplo:
```json
{
  "document": {...},
  "parameters": {
     "resolucion": "3333",
     "header": "XXXX",
     "extras":  [
         {"name": "VENDEDOR", "value": "XXXX"}
      ]
  }
}
```

**Comment by scriptnet** [comment]
Quise agregar una columna más en detalle de una venta para mi PDF, en mi caso es peso, y eh agregado estas lineas de código.
1. config/serializer/Sale.SaleDetail.yml
<img width="153" alt="CAP1" src="https://github.com/giansalex/lycet/assets/38543823/51c43361-78fe-4d4b-904e-43e99b57437d">

2. vendor/greenter/core/src/Core/Model/Sale/SaleDetail.php
<img width="353" alt="CAP2" src="https://github.com/giansalex/lycet/assets/38543823/0c26fecd-42fe-4d74-aca2-314f66bc67a6">
<img width="460" alt="CAP3" src="https://github.com/giansalex/lycet/assets/38543823/12cd9978-9dba-4f49-b08d-9d8b8d7f6087">
<img width="647" alt="CAP4" src="https://github.com/giansalex/lycet/assets/38543823/0aa1a013-c0a7-418c-bdc4-ac52db6068d0">
<img width="183" alt="CAP5" src="https://github.com/giansalex/lycet/assets/38543823/75c2a1c5-9bba-4753-9a4c-a7a5ad5cc934">

4. Y EN invoice.html.twig, capturas la variable asi! 

<img width="144" alt="CAP6" src="https://github.com/giansalex/lycet/assets/38543823/50fdf50b-18ce-4df0-979a-9d08bdc4b061">

QUIERO SABER SI ES LO CORRECTO?, POR EL MOMENTO ME ESTA FUNCIONANDO GENIAL GRACIAS ✌️

**Comment by giansalex** [comment]
@scriptnet si, es una forma
