### ISSUE TITLE
Guardar Archivos

### ISSUE THREAD

**Issue by ajahuanex** [giansalex/lycet#108]
Para guardar los archivos generados por `Lycet` (ya sea el XML, PDF, CDR, ZIP), dentro de un directorio así como en https://github.com/giansalex/greenter-sample, que pasos hay que seguir.

**Comment by giansalex** [comment]
Hola, en este archivo `src/Service/DocumentRequest.php`, allí antes de enviar la respuesta, se deberia guardar los archivos.

**Comment by ajahuanex** [comment]
Me funciona, al generar PDF y XML, lo que aun no logro es guardar el CDR y justo hoy la hay problemas con la conexion a Sunat.
![Screenshot_3](https://user-images.githubusercontent.com/2767765/60288732-784b3d00-98da-11e9-9ead-cc7e078dc8f4.png)

**Comment by giansalex** [comment]
Con el problema del servicio, no se podra obtener el CDR, cuando el servicio vuelva a estar activo, me comentas si se te presenta otro problema.
