### ISSUE TITLE
modelo json ubl 2.1

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/lycet#11]
buenas tardes @giansalex , tendrás algún modelo de json para ubl 2.1?
![json 2_1](https://user-images.githubusercontent.com/31812268/47268630-cd97a900-d518-11e8-98af-34224632ef61.png)

{
  "tipoDoc": "01",
  "serie": "F001",
  "correlativo": "123",
  "fechaEmision": "2017-10-02T00:00:00-05:00",
  "client": {
    "tipoDoc": "6",
    "numDoc": "20384203133",
    "rznSocial": "ZV DISTRIBUIDORES S.A.C.",
    "address": {
 
      "direccion": "AV. SANTA ELVIRA MZA. E LOTE. 1 (VILLA SOL) - LOS OLIVOS LIMA LIMA PERU"
    }
  },
  "company": {
    "ruc": "20480072872",
    "razonSocial": "PESQUERA DIAMANTE S.A.",
    "nombreComercial": "PESQUERA DIAMANTE S.A.",
    "address": {
      "ubigueo": "150131",
      "codigoPais": "51",
      "departamento": "LIMA",
      "provincia": "LIMA",
      "distrito": "SAN ISIDRO",
      "urbanizacion": "-",
      "direccion": "CAL. AMADOR MERINO REYNA NRO. 307 (EDIFICIO NACIONAL PISO 12 Y 13)"
    }
  },
  "tipoMoneda": "PEN",
  "valorVenta":300,
  "sumOtrosCargos": 0,
  "mtoOperGravadas": 200,
  "mtoOperInafectas": 0,
  "mtoOperExoneradas": 100,
  "mtoIGV": 36,
  "mtoISC": 0,
  "totalImpuestos":36,
  "mtoOtrosTributos": 0,
  "mtoImpVenta": 336,
  "details": [
    {
      "unidad": "NIU",
      "cantidad": 2,
      "codProducto": "P0D1",
      "codProdSunat": "string",
      "descripcion": "PROD 1",
      "mtoValorUnitario": 100,
      "descuento": 0,
      "igv": 36,
      "tipAfeIgv": "10",
      "mtoPrecioUnitario": 118,
      "mtoValorVenta": 200,
      "porcentajeIgv": 18,
       "totalImpuestos":36
    },
    {
      "unidad": "KG",
      "cantidad": 2,
      "codProducto": "P0D2",
      "codProdSunat": "string",
      "descripcion": "PROD 2",
      "mtoValorUnitario": 50,
      "descuento": 0,
      "igv": 0,
      "tipAfeIgv": "20",
      "mtoPrecioUnitario": 50,
      "mtoValorVenta": 100,
      "porcentajeIgv": 0,
      "totalImpuestos":0
    }
  ],
  "legends": [
    {
      "code": "1000",
      "value": "SON DOSCIENTOS TREINTA Y SEIS CON 00/100 SOLES"
    }
  ],
  "tipoOperacion": "0101",
  "fecVencimiento": "2017-10-02T00:00:00-05:00",
  "sumDsctoGlobal": 0,
  "mtoDescuentos": 0,
  "mtoOperGratuitas": 0,
  "totalAnticipos": 0,
  "compra": "O-C 100"
 
}

**Comment by giansalex** [comment]
Para que funcione esta muestra, debes actualizar el codigo con los últimos cambios de este repositorio.
```json
  {
    "ublVersion": "2.1",
   "tipoOperacion": "0101",
    "tipoDoc": "01",
    "serie": "F001",
    "correlativo": "111",
    "fechaEmision": "2018-01-20T12:34:00+01:00",
    "client": {
      "tipoDoc": "6",
      "numDoc": "20546687668",
      "rznSocial": "COMPANY SAC"
    },
    "company": {
      "ruc": "20123456789",
      "razonSocial": "LYCET COMPANY SAC",
      "nombreComercial": "COMPANY ",
      "address": {
        "ubigueo": "150101",
        "codigoPais": "PE",
        "departamento": "LIMA",
        "provincia": "LIMA",
        "distrito": "LIMA",
        "urbanizacion": "-",
        "direccion": "AV ITALIA"
      }
    },
    "tipoMoneda": "PEN",
    "mtoOperGravadas": 100,
     "mtoOperInafectas": 0,
    "mtoOperExoneradas": 0,
    "mtoIGV": 18,
    "totalImpuestos": 18,
    "valorVenta": 100,
    "mtoImpVenta": 118,
    "details": [
      {
        "unidad": "NIU",
        "cantidad": 12,
        "codProducto": "string",
        "descripcion": "PRODUCTO 1",
        "mtoValorUnitario": 100,
        "mtoBaseIgv": 100,
        "porcentajeIgv": 18.0,
        "igv": 18,
        "tipAfeIgv": "10",
        "TotalImpuestos": 18,
        "mtoPrecioUnitario": 118,
        "mtoValorVenta": 100
      }
    ],
    "legends": [
      {
        "code": "1000",
        "value": "SON CIEN CON 00/100 SOLES"
      }
    ]
  }
```
> Aún se tendrá que hacer algunos ajustes en swagger y el validador

**Comment by DeveloperRafael1996** [comment]
COMO ACTUALIZO LOS REPOSITORIOS
