### ISSUE TITLE
Error en pruebas con swagger

### ISSUE THREAD

**Issue by heiner25** [giansalex/lycet#12]
Estoy probando la api lycet desde swagger pero al momento de usar /invoice/send se tiene como respuesta: TypeError: Failed to fetch. A que se debe esto o estoy haciendo algo mal?

**Comment by giansalex** [comment]
Puedes configurar siguiendo esta [especificacion](https://github.com/giansalex/lycet#archivos-requeridos)

**Comment by heiner25** [comment]
ok gracias, con eso se solucionó el problema
