### ISSUE TITLE
 Archivo invoicestring.xml.twig no encontrado en la api invoice

### ISSUE THREAD

**Issue by jzea** [giansalex/lycet#121]
hola Giancarlos,
al realizar la llamada a la api invoice me da el error que no se puede encontrar la plantilla  invoicestring.xml.twig
![image](https://user-images.githubusercontent.com/17608454/62013003-bc886200-b152-11e9-99e2-2f12245c8e8c.png)

**Comment by giansalex** [comment]
Hola, es porque estas enviando datos incorrectos en los campos.
Aqui hay unas muestras de json a enviar
[payload.zip](https://github.com/giansalex/lycet/files/3439654/payload.zip)

**Comment by jzea** [comment]
gracias
