### ISSUE TITLE
error al generar pdf 

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/lycet#13]
Buenas noches @giansalex, que crees que estoy haciendo mal, el xml y cdr si esta normal, el error me muestra cuando utilizo el api "http:://localhost:8000/api/v1/invoice/pdf?token=123456".
![pdf_lycet_rror](https://user-images.githubusercontent.com/31812268/47599948-998c1000-d97e-11e8-83ef-b86e2488de27.png)

**Comment by giansalex** [comment]
Tienes instalado wkhtmltopdf? Puedes ejecutar el siguiente comando en la consola de windows
```
wkhtmltopdf http://google.com google.pdf
```

**Comment by JHONQUISPEFLORES** [comment]
SI ACABO DE INSTALARLO EN WINDOWS @giansalex, PERO PARA QUE FUNCIONE EL COMANDO wkhtmltopdf http://google.com google.pdf, TENGO QUE EJECUTARLO DESDE SU CARPETA INSTALADA.
![convertir a pdf](https://user-images.githubusercontent.com/31812268/47604975-358d3a00-d9c6-11e8-953c-8eec903964b8.png)

**Comment by giansalex** [comment]
Entonces en el archivo `.env` que esta en la raiz del proyecto, hay una configuracion `WKHTMLTOPDF_PATH `, alli debes colocar la ruta completa de `wkhtmltopdf.exe`

**Comment by JHONQUISPEFLORES** [comment]
SI ESTOY HACIENDO ESO PROBE CON UNA "\" Y DOS "\\", 
WKHTMLTOPDF_PATH=C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe
PERO ME BOTA UN ERROR.

**Comment by JHONQUISPEFLORES** [comment]
@giansalex, CREO K YA ESTA, ERA POR LOS ESPACIOS EN LA RUTA, LE AGREGUE LAS COMILLAS
WKHTMLTOPDF_PATH="C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"

**Comment by giansalex** [comment]
Si, eso mismo iba a decir

**Comment by JHONQUISPEFLORES** [comment]
PERO SI EL RESULTADO LO QUIERO CONSUMIR (VISUALIZAR) DESDE OTRO APLICATIVO, QUE DEBO HACER?

**Comment by giansalex** [comment]
El api retorna el pdf como un archivo adjunto, si has descargado archivos de la web de cualquier otro sitio, es de la misma forma, leer los bytes y escribirlo en disco.

**Comment by JHONQUISPEFLORES** [comment]
OK, MUCHAS GRACIAS @giansalex.

**Comment by JHONQUISPEFLORES** [comment]
aunque agregando en el template xml invoice2.1.xml.twig, estaría igual

**Comment by JHONQUISPEFLORES** [comment]
le agregue en el template, pero no refleja el cambio, imagino que debe ser por el cache, en donde puedo cambiar eso?

**Comment by giansalex** [comment]
Eliminando la carpeta /var

**Comment by giansalex** [comment]
si, eso serian los cambios.
- Credenciales CLAVE SOL de usuario secundario con permisos para FE
- Certificado previamente registrado en sunat, en formato .pem (Public & Private key)
- URL del servicio de Producción

**Comment by JHONQUISPEFLORES** [comment]
GRACIAS @giansalex, res un genio.

**Comment by giansalex** [comment]
Si tienes otra consulta, crea un nuevo issue, en este no debió tocarse temas que no tenian relación con el titulo.

**Comment by heiner25** [comment]
@giansalex @JHONQUISPEFLORES como soluciono el problema que al generar el pdf usando postman y en preview se descarga el pdf pero en blanco? intenté borrando la carpeta var, pero aun persiste el mismo problema

**Comment by JHONQUISPEFLORES** [comment]
Estimado @heiner25 , tampoco pude solucionarlo sigo con el pdf en blanco, eso de eliminar /var, era para no reflejar los cambios en el template.

**Comment by giansalex** [comment]
Existe un boton en la derecha que dice **Download**, alli si se puede ver el pdf correctamente

**Comment by JHONQUISPEFLORES** [comment]
si funciona desde Download @giansalex, MUCHAS GRACIAS.
