### ISSUE TITLE
Consulta sobre manejo Configuración de la API

### ISSUE THREAD

**Issue by heiner25** [giansalex/lycet#14]
@giansalex tengo 2 dudas espero puedas ayudarme:
1. Entiendo que en el archivo .env se coloca un token por defecto 123456, como podria generar un token más sofisticado? y en el cliente como sería su uso?
2. Según entiendo, la API solo podría ser usado por un cliente a la vez? ya que requiere clave SOL y el certificado digital, si es así podrias orientarme o darme la idea masomenos de cómo podria hacer para usar la misma API con diferentes clientes los cuales tienen su propio logo y certificado digital?

**Comment by heiner25** [comment]
@giansalex podrias ayudarme, darme una idea al menos de como podria hacer? agradezco desde ya todo tu apoyo

**Comment by leog1992** [comment]
Buenas noches, yo diría crear una tabla clientes, donde guardar clave sol y contraseña por RUC, y la dirección y nombre del archivo env, y nombre del archivo PEM. 
Según el token acceder a sus datos.

El token puedes encriptarlo con md_5 de repente hay otro mejor

**Comment by heiner25** [comment]
@leog1992 gracias por darte el tiempo de responder y por tu ayuda

**Comment by giansalex** [comment]
Lycet solo esta hecha para ser usada por una empresa, pero podrías seguir lo que dice @leog1992 para lograr lo que necesitas.

**Comment by giansalex** [comment]
Para un token seguro puedes generarlo con openssl
openssl rand -base64 32
