### ISSUE TITLE
Usuario Secundario envió a producción

### ISSUE THREAD

**Issue by OBSK** [giansalex/lycet#15]
Hola  @giansalex acabo de enviar el comprobante con la url de producción, pero recibí un mensage de error con codigo 0111 **No tiene el perfil para enviar comprobantes electronicos**, ¿tengo que poner en los archivos .env el usuario y clave sol, o el usuario secundario que generé en el portal de la Sunat?. Saludos

**Comment by giansalex** [comment]
Debe ir la clave sol del Usuario Secundario, pero esto puede tomar 1 día después de crearlo para que tome efecto.

**Comment by giansalex** [comment]
@OBSK , el problema persiste?

**Comment by OBSK** [comment]
Hola @giansalex, si, sigue el error con código **0111- No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy.**, con el SOL_USER y SOL_PASS de mi usuario secundario, voy a crear otro por si las dudas, el portal es demasiado lento.

**Comment by AnthonyLJ96** [comment]
Tal vez no le has dado el rol correspondiente al usuario en el portal de sunat.

**Comment by giansalex** [comment]
Hola @eilsongithub, si no puedes enviar con el usuario secundario, intenta con el usuario principal.

**Comment by eilsongithub** [comment]
Acabo de probar con el principal.... y sigue el error.

**Comment by eilsongithub** [comment]
enviando a esta ruta:FE_URL='https://e-factura.sunat.gob.pe:443/ol-ti-itemision-otroscpe-gem/billService'
me sale este error:
![image](https://user-images.githubusercontent.com/44086967/49544614-3fe60200-f8a9-11e8-9356-801c357343f3.png)

**Comment by eilsongithub** [comment]
he visto que me sale este error ?

![image](https://user-images.githubusercontent.com/44086967/49545664-3b6f1880-f8ac-11e8-922e-6a5490cd2573.png)

**Comment by giansalex** [comment]
Ese nombre, parece estar correcto, tipo 01: indica Factura
