### ISSUE TITLE
FACTURA ACEPTADA CON OBSERVACIONES

### ISSUE THREAD

**Issue by VictorCampoverde29** [giansalex/lycet#183]
Estoy enviando mis facturas en producción pero el cdr me indica observaciones,para el caso de **FACTURAS GRAVADAS:**
4293 - El importe total de impuestos por linea no coincide con la sumatoria de los impuestos por l&#237;nea. - Error en la linea: 1: 4293 (nodo: "cac:TaxTotal/cbc:TaxAmount" valor: "0.00")
4287 - El precio unitario de la operaci&#243;n que est&#225; informando difiere de los calculos realizados en base a la informacion remitida - Error en la linea: 1: 4287 (nodo: "cac:AlternativeConditionPrice/cbc:PriceAmount" valor: "10")
4310 - La sumatoria del Total del valor de venta mas los impuestos no concuerda con la base imponible - INFO : 4310 (nodo: "/" valor: "")
**FACTURAS EXONERADAS:**
4310 - La sumatoria del Total del valor de venta más los impuestos no concuerda con la base imponible - INFO : 4310 (nodo: \"/\" valor:"")

**JSON GRAVADAS:**
{
  "ublVersion": "2.1",
  "tipoOperacion": "0101",
  "tipoDoc": "01",
  "serie": "F001",
  "correlativo": "00000068",
  "fechaEmision": "2019-12-02T19:25:13+01:00",
  "client": {
    "tipoDoc": "6",
    "numDoc": "20603343710",
    "rznSocial": "CHIN NEGOCIOS Y TRANSPORTES S.A.C.",
    "address": {
      "ubigueo": "140105",
      "codigoPais": "PE",
      "departamento": "-",
      "provincia": "-",
      "distrito": "-",
      "urbanizacion": "-",
      "direccion": "AV. MARIANO CORNEJO NRO. 425 C.P. CPM. NUEVO SAN LORENZO III ETAPA LAMBAYEQUE - CHICLAYO - JOSE LEONARDO ORTIZ",
      "codLocal": "0000"
    },
    "email": null,
    "telephone": null
  },
  "company": {
    "ruc": "20604473081",
    "razonSocial": "ASIU COSTA SAC",
    "nombreComercial": "ASIU COSTA SAC",
    "address": {
      "ubigueo": "140105",
      "codigoPais": "PE",
      "departamento": "-",
      "provincia": "-",
      "distrito": "-",
      "urbanizacion": "-",
      "direccion": "PRINCIPAL:CAL.CARLOS CASTAÑEDA NRO. 261 P.J. FRANCISCO CABRERA LAMBAYEQUE - CHICLAYO - JOSE LEONARDO ORTIZ/",
      "codLocal": "0000"
    },
    "email": null,
    "telephone": null
  },
  "tipoMoneda": "PEN",
  "mtoOperGravadas": 100,
  "mtoOperInafectas": 0,
  "mtoOperExoneradas": 0,
  "mtoOperExportacion": 0,
  "mtoIGV": 18,
  "icbper": 0,
  "totalImpuestos": 18,
  "valorVenta": 100,
  "mtoImpVenta": 118,
  "SumDsctoGlobal": 0,
  "MtoDescuentos": 0,
  "Descuentos": null,
  "details": [
    {
      "unidad": "ZZ",
      "cantidad": 2,
      "codProducto": "-",
      "descripcion": "PRUEBA DE SISTEMAS",
      "mtoValorUnitario": 50,
      "mtoBaseIgv": 100,
      "porcentajeIgv": 18,
      "igv": 18,
      "tipAfeIgv": "10",
      "factorIcbper": "0",
      "icbper": "0",
      "TotalImpuestos": 18,
      "mtoPrecioUnitario": 59,
      "mtoValorVenta": 100
    }
  ],
  "legends": [
    {
      "code": "1000",
      "value": "CIENTO DIECIOCHO CON 00 /100 SOLES"
    }
  ]
}
**JSON EXONERADAS:**
{
  "ublVersion": "2.1",
  "tipoOperacion": "0101",
  "tipoDoc": "01",
  "serie": "F005",
  "correlativo": "00002284",
  "fechaEmision": "2019-12-03T11:10:25+01:00",
  "client": {
    "tipoDoc": "6",
    "numDoc": "20603343710",
    "rznSocial": "CHIN NEGOCIOS Y TRANSPORTES S.A.C.",
    "address": {
      "ubigueo": "140105",
      "codigoPais": "PE",
      "departamento": "-",
      "provincia": "-",
      "distrito": "-",
      "urbanizacion": "-",
      "direccion": "AV. MARIANO CORNEJO NRO. 425 C.P. CPM. NUEVO SAN LORENZO III ETAPA LAMBAYEQUE - CHICLAYO - JOSE LEONARDO ORTIZ",
      "codLocal": "0000"
    }
  },
  "company": {
    "ruc": "20604209316",
    "razonSocial": "ASIU SELVA SAC",
    "nombreComercial": "ASIU SELVA SAC",
    "address": {
      "ubigueo": "160101",
      "codigoPais": "PE",
      "departamento": "-",
      "provincia": "-",
      "distrito": "-",
      "urbanizacion": "-",
      "direccion": "PRINCIPAL:JR. TRUJILLO NRO.726A P.J. SAN ANTONIO LORETO - MAYNAS - IQUITOS/SUCURSAL:CAR.FEDERICO BASADRE KM. 3600 UCAYALI - CORONEL PORTILLO - YARINACOCHA\t",
      "codLocal": "0000"
    }
  },
  "tipoMoneda": "PEN",
  "mtoOperExoneradas": 100,
  "mtoIGV": 0,
  "totalImpuestos": 0,
  "valorVenta": 100,
  "mtoImpVenta": 100,
  "details": [
    {
      "unidad": "ZZ",
      "cantidad": 1,
      "codProducto": "-",
      "descripcion": "PRUEBA DE SISTEMAS",
      "mtoValorUnitario": 100,
      "mtoBaseIgv": 100,
      "porcentajeIgv": 0,
      "igv": 0,
      "tipAfeIgv": "20",      
      "TotalImpuestos": 0,
      "mtoPrecioUnitario": 100,
      "mtoValorVenta": 100
    }
  ],
  "legends": [
    {
      "code": "1000",
      "value": "CIEN CON 00 /100 SOLES"
    }
  ]
}
¿Alguna sugerencia?

**Comment by giansalex** [comment]
Probablemente falta el `subTotal`

**Comment by VictorCampoverde29** [comment]
Agrege la columna subtotal pero sigo teniendo los mismos errores 
**JSON:**
{
  "ublVersion": "2.1",
  "tipoOperacion": "0101",
  "tipoDoc": "01",
  "serie": "F001",
  "correlativo": "00000072",
  "fechaEmision": "2019-12-03T16:38:58+01:00",
  "client": {
    "tipoDoc": "6",
    "numDoc": "20603343710",
    "rznSocial": "CHIN NEGOCIOS Y TRANSPORTES S.A.C.",
    "address": {
      "ubigueo": "140105",
      "codigoPais": "PE",
      "departamento": "-",
      "provincia": "-",
      "distrito": "-",
      "urbanizacion": "-",
      "direccion": "AV. MARIANO CORNEJO NRO. 425 C.P. CPM. NUEVO SAN LORENZO III ETAPA LAMBAYEQUE - CHICLAYO - JOSE LEONARDO ORTIZ",
      "codLocal": "0000"
    }
  },
  "company": {
    "ruc": "20604473081",
    "razonSocial": "ASIU COSTA SAC",
    "nombreComercial": "ASIU COSTA SAC",
    "address": {
      "ubigueo": "140105",
      "codigoPais": "PE",
      "departamento": "-",
      "provincia": "-",
      "distrito": "-",
      "urbanizacion": "-",
      "direccion": "PRINCIPAL:CAL.CARLOS CASTAÑEDA NRO. 261 P.J. FRANCISCO CABRERA LAMBAYEQUE - CHICLAYO - JOSE LEONARDO ORTIZ/",
      "codLocal": "0000"
    },
    "email": null,
    "telephone": null
  },
  "tipoMoneda": "PEN",
  "mtoOperGravadas": 100,
  "mtoOperInafectas": 0,
  "mtoOperExoneradas": 0,
  "mtoOperExportacion": 0,
  "mtoIGV": 18,
  "icbper": 0,
  "totalImpuestos": 18,
  "subTotal": 100,
  "valorVenta": 100,
  "mtoImpVenta": 118,
  "SumDsctoGlobal": 0,
  "MtoDescuentos": 0,
  "Descuentos": null,
  "details": [
    {
      "unidad": "ZZ",
      "cantidad": 1,
      "codProducto": "-",
      "descripcion": "PRUEBA DE SISTEMAS",
      "mtoValorUnitario": 100,
      "mtoBaseIgv": 100,
      "porcentajeIgv": 18,
      "igv": 18,
      "tipAfeIgv": "10",
      "factorIcbper": "0",
      "icbper": "0",
      "TotalImpuestos": 18,
      "mtoPrecioUnitario": 118,
      "mtoValorVenta": 100
    }
  ],
  "legends": [
    {
      "code": "1000",
      "value": "CIENTO DIECIOCHO CON 00 /100 SOLES"
    }
  ]
}

**Comment by VictorCampoverde29** [comment]
Si tienes un ejemplo de JSON te lo agradeceria Giancarlo

**Comment by giansalex** [comment]
Ejecuta `composer install` para que se actualicen los paquetes y borra la carpeta `/var` .

**Comment by VictorCampoverde29** [comment]
Hola Giancarlos la Exonerada logre solucionarla actualizando lo que me indicaste ahora tengo problemas con mi comunicaciones de baja me retorna el siguiente mensaje:
La fecha de generación del resumen debe ser igual a la fecha consignada en el nombre del archivo - La fecha de generación del resumen debe ser igual a la fecha consignada en el nombre del archivo
		         Detalle:xxx.xxx.xxx value='ticket: 201904758429999 error: INFO : 2346 (nodo: "VoidedDocuments/cbc:ID" valor: "RA-20191204-67")'

Este es mi JSON:
{
  "correlativo": "67",
  "fecGeneracion": "2019-12-04T00:43:08+01:00",
  "fecComunicacion": "2019-12-04T00:43:08+01:00",
  "company": {
    "ruc": "20604209316",
    "razonSocial": "ASIU SELVA SAC",
    "nombreComercial": null,
    "address": null,
    "email": null,
    "telephone": null
  },
  "details": [
    {
      "tipoDoc": "01",
      "serie": "F005",
      "correlativo": "00002286",
      "desMotivoBaja": "PRUEBA DE SISTEMAS"
    }
  ]
}
Y al momento de generar el XML me cambia la fecha enviada por un dia anterior:
![image](https://user-images.githubusercontent.com/26303858/70119752-fdc8db00-1638-11ea-9346-f87dde5e52a6.png)

**Comment by giansalex** [comment]
justo aqui https://github.com/giansalex/lycet#configuraciones indica lo que falta, configurar la zona horaria

**Comment by VictorCampoverde29** [comment]
Ola giancarlos te comento el apirest esta en mi hosting con la versión que
estaba trabajando funcionaba normal ahora que actualize el repositorio me
presenta ese error

**Comment by giansalex** [comment]
Podrias usar en fecha algo como `2019-12-04T00:00:00-05:00`

**Comment by VictorCampoverde29** [comment]
Giansalex seguí el formato de fecha indicado en el comentario de arriba,problema solucionado
