### ISSUE TITLE
Hay alguna parte donde se está enviando el monto de descuento?

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#184]
Quisiera saber si se envia de alguna forma los descuentos

**Comment by giansalex** [comment]
Puedes seguir el ejemplo de https://giansalex.github.io/greenter/examples/descuento-linea/
en este caso en formato json debería ir como:
```json
{
  "descuentos": [
  {
    "codTipo": "00",
    "montoBase": 200,
    "factor": 0.10,
    "monto": 20
  }
  ]
}
```

**Comment by OD-n** [comment]
Gracias @giansalex , acabo de encontrarlo

**Comment by OD-n** [comment]
Una ultima pregunta, existe la forma de enviar descuento para las boletas por resumen diario?, en la documentación SWAGGER encuentro operaciones inafectas, gratuitas, exoneradas pero no estoy seguro si alguna se usará para el envío de descuentos; gracias de antemano

**Comment by giansalex** [comment]
Existe el campo, pero sunat en sus validaciones solo permite que se envié otros Cargos, no descuentos.
