### ISSUE TITLE
Lycet producción

### ISSUE THREAD

**Issue by wilmerortiz** [giansalex/lycet#199]
Hola giansalex 
Una consuta:
¿Que parametros debo configurar para cambiar de BETA  a PRODUCCIÓN?

He cambiado las rutas por defecto por estas:
FE_URL=https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService
RE_URL=https://e-factura.sunat.gob.pe/ol-ti-itemision-otroscpe-gem/billService
GUIA_URL=https://e-guiaremision.sunat.gob.pe/ol-ti-itemision-guia-gem/billService

Cuando envio me sale este error:
0110: No se pudo obtener la informacion del tipo de usuario.

Ya he creado el usuario secundario y asignado los permisos correspondientes y ya es más de 1 día.

**Comment by giansalex** [comment]
Hola @wilmerortiz, no habia visto ese error antes, puedes probar con tu usuario principal.

**Comment by wilmerortiz** [comment]
Gracias por tu pronta respuesta, aplicaré tu sugerencia de usar al usuario principal

**Comment by wilmerortiz** [comment]
Hola, @giansalex ya solucioné ese problema, pero ahora tengo una observación del codigo 4317, lo busque en la lista de error y dice 4317: Debe consignar el total precio de venta.

**Comment by giansalex** [comment]
Hola @wilmerortiz, te falta enviar el `subTotal`

https://github.com/giansalex/greenter-sample/blob/master/examples/factura.php#L29

**Comment by wilmerortiz** [comment]
Utilizando la api lycet sería así:
...
subTotal : 100
. ..
O cuál es la variable que debería ir.??

**Comment by giansalex** [comment]
si, ese es el campo

**Comment by wilmerortiz** [comment]
Gracia @giansalex . Ya solucioné todos los errores que tenía. Cerraré el Issues.

**Comment by giansalex** [comment]
Ok, listo.
