### ISSUE TITLE
El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket:

### ISSUE THREAD

**Issue by guto80** [giansalex/lycet#207]
hola Giancarlos, Al querer enviar una comunicación de baja me sale este error, los demás esta bien. actualice lo ultimo de lycet, configure bien la zona horaria pero persiste el error.

![Sin título](https://user-images.githubusercontent.com/47509408/75015311-4d5bbd80-5456-11ea-8ba7-cb0ec8f28c1c.png)

este es el código que estoy tomando de ejemplo:

[payload.zip](https://github.com/giansalex/lycet/files/4234909/payload.zip)

**Comment by giansalex** [comment]
Hola @guto80, el numero `10413339516`, es el ruc que enviaste?

**Comment by guto80** [comment]
Si, es el RUC con el que se genera las ventas

**Comment by giansalex** [comment]
Segun la imagen, se envía `10413339516---1.zip`, cuando debería estar en este formato: `10413339516-RA-20200220-1.zip`, es Beta?, yo he probado un envio y funciona bien.
![image](https://user-images.githubusercontent.com/14926587/75049318-fe367c80-5497-11ea-87c4-3de05f52d761.png)

**Comment by guto80** [comment]
Buenas noches, si efectivamente estoy en modo Beta, lo curioso es que si envió con petstore swagger envía bien, pero al enviar desde mi sistema o desde postman me sale ese error, con las facturas y resúmenes de boletas todo esta bien sin problemas, solo pasa cuando intento dar de baja las facturas.

**Comment by giansalex** [comment]
Talvez la ruta a donde esta enviando no es la que debería.
