### ISSUE TITLE
Error de resumen diario

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#214]
Cuando intenté enviar un resumen diario tengo el siguiente problema: 

> La fecha de generación del resumen debe ser igual a la fecha consignada en el nombre del archivo - La fecha de generación del resumen debe ser igual a la fecha consignada en el nombre del archivo

No sé por que se produce ese error, si alguien puede ayudarme se lo agradecería, muchas gracias.

**Comment by giansalex** [comment]
Hola @OD-n , que valores estas enviando en estos campos?
Has configurado el timezone en el php.ini: `date.timezone ="America/Lima"`

**Comment by OD-n** [comment]
No tengo ese item en el php.ini de la api; solo tengo esto: 
`display_errors = On
max_execution_time = 90
max_input_time = -1
max_input_vars = 1000
memory_limit = 128M
post_max_size = 8M
session.gc_maxlifetime = 1440
session.save_path = "/opt/alt/php72/var/lib/php/session"
upload_max_filesize = 2M
zlib.output_compression = On`

**Comment by OD-n** [comment]
la añadiré, disculpa, apenas acaba de pasar este problema, anteriormente siempre estuvo funcionando, no sé si algo cambio
