### ISSUE TITLE
Error formato de Fecha Invalido

### ISSUE THREAD

**Issue by jeanpaulrd1** [giansalex/lycet#228]
Hola, al intentar enviar una factura o boleta me da un error de formato de fecha incorrecto. He configurado el time/zone en el php.ini. Me podrías ayudar por favor? Gracias de antemano.

![error-api](https://user-images.githubusercontent.com/19482586/78077187-877d8080-736d-11ea-87a1-d2c692667c0a.PNG)

![image](https://user-images.githubusercontent.com/19482586/78077586-3cb03880-736e-11ea-90f0-569b102bb8f9.png)

**Comment by giansalex** [comment]
Hola @jeanpaulrd1, el formato de fecha debe ser `2020-02-20T23:44:35-05:00"`

**Comment by jeanpaulrd1** [comment]
Gracias !
