### ISSUE TITLE
No se puede leer (parsear) el archivo XML

### ISSUE THREAD

**Issue by jeanpaulrd1** [giansalex/lycet#229]
Hola Giancarlos, me podrías ayudar con este error que aparece al intentar enviar una factura o boleta.

![image](https://user-images.githubusercontent.com/19482586/78308289-bb8fa780-750d-11ea-86c2-b52f2ac64f70.png)

Gracias.

**Comment by giansalex** [comment]
Hola @jeanpaulrd1, estas enviando valor en el campo `codProdGS1`?

**Comment by jeanpaulrd1** [comment]
@giansalex , si le estoy enviando

![image](https://user-images.githubusercontent.com/19482586/78317915-31edd300-7529-11ea-9e69-e50af143db33.png)

**Comment by giansalex** [comment]
Parece que había problema escondido, relacionado con el uso de `codProdSunat` y `codProdGS1`, mañana lo revisaré a detalle,

**Comment by giansalex** [comment]
Hola @jeanpaulrd1, se corrigió ese problema.

Puedes ejecutar estos comandos para probarlo.
```
git pull
composer install
```

**Comment by jeanpaulrd1** [comment]
@giansalex ahora me aparece esto:

![image](https://user-images.githubusercontent.com/19482586/78389779-f98dd980-75a8-11ea-9a7f-dc8e5ac34cf8.png)


Crees que me puedas pasar una trama de ejemplo, para hacer las pruebas?

**Comment by giansalex** [comment]
Esos son mensajes de validaciones, aquí tienes algunos ejemplos.

[payload.zip](https://github.com/giansalex/lycet/files/4429979/payload.zip)
