### ISSUE TITLE
Modificar pdf de facturas/boletas

### ISSUE THREAD

**Issue by jeanpaulrd1** [giansalex/lycet#264]
Hola @giansalex, una consulta: si quiero modificar el formato de los pdfs, además de modificar el archivo invoice.html.twig que está en la carpeta \vendor\greenter\report\src\Report\Templates, debo modificar algún otro archivo?

**Comment by giansalex** [comment]
Hola @jeanpaulrd1 , solo necesitarias modificar ese archivo y borrar la carpeta `/var`, para ver los cambios reflejados.

**Comment by jeanpaulrd1** [comment]
Gracias por la ayuda @giansalex !
