### ISSUE TITLE
4317	Debe consignar el Total Precio de Venta

### ISSUE THREAD

**Issue by ChristDev** [giansalex/lycet#265]
Buenas noches, utilizo el API Rest Lycet con el client en csharp, pero no me logra generar el campo que SubTotal que creo es el motivo del error 4317. Gracias de antemano por su apoyo

**Comment by giansalex** [comment]
Hola @ChristDev , el campo si esta incluido [aqui](https://github.com/giansalex/lycet/blob/master/config/serializer/Sale.Invoice.yml#L69), tal vez necesitas actualizar el repositorio.

**Comment by ChristDev** [comment]
oh, ya veo no tenia actualizado ello. muchas gracias @giansalex
