### ISSUE TITLE
Descuento no reflejado

### ISSUE THREAD

**Issue by jeanpaulrd1** [giansalex/lycet#269]
Hola @giansalex , una consulta: estoy enviando un descuento global en una factura, pero no se refleja en el xml de respuesta, debo enviarlo en algún otro lado? 

![image](https://user-images.githubusercontent.com/19482586/88205018-c6cc2780-cc11-11ea-9ae3-3d3cb911b7bb.png)

![image](https://user-images.githubusercontent.com/19482586/88205083-dc415180-cc11-11ea-913e-3487d40217c7.png)

**Comment by giansalex** [comment]
Es raro, yo si puedo obtenerlo. 
![image](https://user-images.githubusercontent.com/14926587/88225672-7fa15f00-cc30-11ea-9d6d-a61b6758a0f7.png)

Puedes actualizar el repositorio y borrar la carpeta `var/`.
Tambien una observación, el codigo para Descuento global es `02`, el codigo `00` es para nivel de detalle.

**Comment by jeanpaulrd1** [comment]
@giansalex, le agregué el campo sumDsctoGlobal y ahora si aparece. Como hago para que el pdf muestre el valor del descuento?

![image](https://user-images.githubusercontent.com/19482586/88238334-006b5580-cc47-11ea-92fe-4bc638b90904.png)

**Comment by giansalex** [comment]
@jeanpaulrd1 el modelo de PDF puede ser personalizado, el modelo original no incluye descuentos, pero puedes añadirlo, puedes encontrar una guia [aquí](https://greenter.dev/packages/report/#personalizar).
