### ISSUE TITLE
Imprimir en ticketera

### ISSUE THREAD

**Issue by eilsongithub** [giansalex/lycet#27]
Estimado Giancarlos.

Como puedo hacer para imprimir en ticketera (matricial o termica, con logo y codigo QR), ya que la empresa tiene una ticketera y desea imprimir automáticamente cuando hace la venta en su aplicación. 

Vale decir que actualmente envío un Json desde la aplicación y realiza la generación del PDF con lycet y de ahí imprime el PDF en papel bond y le entrega al cliente pero se demora un poco con este proceso.

Y por su puesto como es un negocio que tiene clientes en cola, desea que la impresión sea rápida. ¿Debe hacerse primero el PDF y mandarla a imprimir?¿de ser así como puedo mandarla a imprimir automáticamente de php? ....  o Directamente imprimir en ticketera sin necesidad de generar pdf?.

Perdón por tu tiempo.

Que me recomiendas ...

**Comment by JHONQUISPEFLORES** [comment]
Hola @eilsongithub , 
yo usaria la libreria https://github.com/mike42/escpos-php, te imprime directo en ticketera incluso en ticketereas en red, "**pero tienes que armar en php lo que vas a imprimir**". lycet te devuelve el xml y hash, solo generarias el QR y si puedes leer el xml para armar tu factura o boleta.

**Comment by giansalex** [comment]
Como dice Jhon, puedes hacer la impresión directa, para que sea lo mas rápido. Para el caso del QR, podria agregarse a este API

**Comment by JHONQUISPEFLORES** [comment]
@giansalex , seria genial el QR en base64.

**Comment by giansalex** [comment]
Hola @JHONQUISPEFLORES , se agregará la ruta para generar el QR.
Referenciado en https://github.com/giansalex/lycet/issues/17
