### ISSUE TITLE
Error Al generar PDF: Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request

### ISSUE THREAD

**Issue by eilsongithub** [giansalex/lycet#270]
Buenas tardes. Recientemente he cambiado de un reseller a un vps. y encuentro que tengo un problema con la api al generar el pdf, sin embargo el xml se genera sin inconveniente.
el error que obtengo al momento de consultar al link
http://xxxxxxx/public/api/v1/invoice/pdf?token=xxxxxxxxx

obtengo esto

**Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.**

**Comment by eilsongithub** [comment]
Alguien me puede ayudar:
Vale decir que la api está en el mismo servidor que el sistema. y por Postman si obtengo el pdf sin problemas.

**Comment by eilsongithub** [comment]
Ahora me sale esto: 
"message": "sh: /home/xxxx/parapdf/wkhtmltopdf: Permission denied"
por postman tambien.

**Comment by giansalex** [comment]
Hola @eilsongithub, tendrias que darle permiso de ejecucion

```sh
sudo chmod +x /home/xxxx/parapdf/wkhtmltopdf
```

**Comment by OD-n** [comment]
Yo tengo el mismo error: 
Cuando quiero descargar el PDF me aparece problemas para cargar: asi que al abrirlo con un editor de texto el contenido tiene el mismo mensaje: pero al convertir la respuesta en PDF
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>`

**Comment by erajuan** [comment]
Podrías compartir algunos datos de prueba, la versión de php.

en general te recomiendo actualizar a la ultima versión.

**Comment by OD-n** [comment]
Gracias, el problema fué las reglas que bloqueaban la peticion explicita del PDF, lo que se tenía que hacer era permitirlas.
En conclusión tenía que ver con el MOD_SECURITY. Gracias a todos.
