### ISSUE TITLE
Json Model - Resumen Diario

### ISSUE THREAD

**Issue by JHONQUISPEFLORES** [giansalex/lycet#28]
Hola @giansalex , estube probando el resumen diario de boletas, pero me bota un error o en que estoy errando??. ("No existe información de serie o número. - Detalle: xxx.xxx.xxx value='ticket: 1550786770356 error: Error en la linea: 1. Solo se acepta informacion de comprobantes de referencia para notas (Credito o debito): el tipo de comprobante es: 03 y debe de ser 07 o 08.')
![image](https://user-images.githubusercontent.com/31812268/53205099-5162be80-35fb-11e9-8419-dd6f4ecfd42a.png)
Ejemplo de prueba 
{
  "correlativo": "003",
  "fecGeneracion": "2019-02-18T12:00:00+02:00",
  "fecResumen": "2019-02-21T12:00:00+00:00",
  "moneda": "PEN",
  "company": {
    "ruc": "20123456789",
    "razonSocial": "REST. MORALY",
    "nombreComercial": "MORALY",
    "address": {
      "ubigueo": "180101",
      "codigoPais": "PE",
      "departamento": "MOQUEGUA",
      "provincia": "MARISCAL NIETO",
      "distrito": "MOQUEGUA",
      "urbanizacion": "-",
      "direccion": "CALLE LIMA 398",
      "codLocal": "0000"
    },
    "email": "ujcm_jhon@hotmail.com",
    "telephone": "997788551"
  },
  "details": [
    {
      "tipoDoc": "03",
      "serieNro": "B001-1",
      "clienteTipo": "1",
      "clienteNro": "42731344",
      "docReferencia": {
        "tipoDoc": "",
        "nroDoc": ""
      },
      "estado": "1",
      "total": "25.00",
      "mtoOperGravadas": "21.19",
      "mtoOperInafectas": 0,
      "mtoOperExoneradas": 0,
      "mtoOperExportacion": 0,
      "mtoOperGratuitas": 0,
      "mtoOtrosCargos": 0,
      "mtoIGV": "3.81",
      "mtoIvap": 0,
      "mtoISC": 0,
      "mtoOtrosTributos": 0
    }
  ]
}

**Comment by giansalex** [comment]
Prueba con esto
```json
{
  "correlativo": "003",
  "fecGeneracion": "2019-02-18T12:00:00+02:00",
  "fecResumen": "2019-02-21T12:00:00+00:00",
  "moneda": "PEN",
  "company": {
    "ruc": "20123456789",
    "razonSocial": "REST. MORALY",
    "nombreComercial": "MORALY",
    "address": {
      "ubigueo": "180101",
      "codigoPais": "PE",
      "departamento": "MOQUEGUA",
      "provincia": "MARISCAL NIETO",
      "distrito": "MOQUEGUA",
      "urbanizacion": "-",
      "direccion": "CALLE LIMA 398"
    }
  },
  "details": [
    {
      "tipoDoc": "03",
      "serieNro": "B001-1",
      "clienteTipo": "1",
      "clienteNro": "42731344",
      "estado": "1",
      "total": "25.00",
      "mtoOperGravadas": "21.19",
      "mtoIGV": "3.81"
    }
  ]
}
```
Los campos que no son obligatorios, no es necesario enviarlo, en este caso el problema era el campo `docReferencia`, que se usa en notas de credito/debito. Y al enviar el objeto vacio, sale el mensaje de error

**Comment by JHONQUISPEFLORES** [comment]
@giansalex , gracias, tenias razón
