### ISSUE TITLE
Habilitar UBL 2.1

### ISSUE THREAD

**Issue by KhanMaytok** [giansalex/lycet#31]
Saludos

Como habilito UBL 2.1?

Estoy obteniendo el error: 

`No está autorizado a enviar comprobantes bajo el formato UBL 2.0 - No está autorizado a enviar comprobantes bajo el formato UBL 2.0. El ruc: 20395419715 debe generar su comprobante en la version UBL 2.1'`

**Comment by KhanMaytok** [comment]
Creo que ya vi la solucion, en https://github.com/giansalex/lycet/issues/11

**Comment by giansalex** [comment]
Si, en el campo "ublVersion"":"2.1"
