### ISSUE TITLE
Me sale error al instalar lycet con Docker

### ISSUE THREAD

**Issue by polchis** [giansalex/lycet#314]
Hola a toda la comunidad,
Tengo la version Docker versión 19.03.13, build 4484c46d9d 
He seguido los pasos de instalación de lycet con docker  pero cuando creo la imagen con el Dockerfile de la carpeta lycet no logra instalar composer o se detiene la instalación en ese paso .... 

![Captura de pantalla de 2020-10-15 18-40-10](https://user-images.githubusercontent.com/622405/96196921-3bafb480-0f16-11eb-91ab-9a905af91b34.png)

en la parte final donde se corta la instalacion sale esto:

![Captura de pantalla de 2020-10-15 18-40-14](https://user-images.githubusercontent.com/622405/96196949-49653a00-0f16-11eb-8c3a-fa976ae4d448.png)

pueden ayudarme por favor????

**Comment by giansalex** [comment]
Hola @polchis , hay un problema con un archivo recientemente agregado que no se esta incluyendo en la imagen.
Haré una corrección sobre eso.
