### ISSUE TITLE
ERROR en virtualhost: Fetch errorPossible cross-origin (CORS) issue

### ISSUE THREAD

**Issue by jwcaceres** [giansalex/lycet#323]
He instalado Lycet en un servidor en la nube y con un subdominio, pero me sale el siguiente error:

'''
Fetch errorFailed to fetch https://lycet.midominio.com/swagger
Fetch errorPossible cross-origin (CORS) issue? The URL origin (https://lycet.midominio.com) does not match the page (https://petstore.swagger.io). Check the server returns the correct 'Access-Control-Allow-*' headers.

'''
El servidor tiene las siguientes características:
Ubuntu 20.04
Php 7.4
Apache 2
SSL

He intentado con el .htaccess y tampoco funciona :
Header add Access-Control-Allow-Origin "*"

Gracias por la ayuda

**Comment by giansalex** [comment]
Hola @jwcaceres , hay una [versión desplegada](https://petstore.swagger.io/?url=https://greenter-lycet.herokuapp.com/swagger) en heroku, la configuracion se toma desde `.env`

https://github.com/giansalex/lycet/blob/a5a64d1e14cd58c0fbaffe119275b0d7c1cb6111/.env#L24
