### ISSUE TITLE
Rate limit?

### ISSUE THREAD

**Issue by KhanMaytok** [giansalex/lycet#33]
Hola, quizá esta pregunta no pertenece a lycet, pero quisiera saber si SUNAT tiene un rate limit para enviar comprobantes?

Porque cuando intento enviar muchas facturas seguidas me aparece un error de 

```
No tiene el perfil para enviar comprobantes electronicos - Detalle: Rejected by policy
```

el error es aleatorio. a veces aparece, a veces no

**Comment by giansalex** [comment]
Hola @KhanMaytok , sunat no indica un limite hasta ahora, cuando entre en operación las OSE, alli si habrá un limite, ya que solo lo deberán usar empresas que emitan pocos comprobantes.
Ese error tampoco esta relacionado, debe haber problemas en los servicios de SUNAT

**Comment by KhanMaytok** [comment]
Sí, lo que hice fue marcar esos comprobantes que tenían el error y reenviarlos y reenviarlos hasta que fueron aprobados.
