### ISSUE TITLE
CONSULT ENDPOINT "empresas.json" - Multiempresa

### ISSUE THREAD

**Issue by jose7847** [giansalex/lycet#333]
Hola @giansalex una consulta e agregado en la carpeta "data" el archivo "empresas.json"

> `{ "20000000001": { "SOL_USER": "20000000001MODDATOS", "SOL_PASS": "moddatos", "certificate": "20000000001-cert.pem", "logo": "20000000001-logo.png" }, "20000000002": { "SOL_USER": "20000000002MODDATOS", "SOL_PASS": "moddatos", "certificate": "20000000002-cert.pem", "logo": "20000000002-logo.png" } }`

también agregue los archivos(.pem y el logo) directamente, bueno como es que puedo ahora hacer la petición por cada empresa?? si con una empresa era "localhost:8080/api/v1/send?token=123456" pero ahora que esta como multiempresa como seria?
hay un endpoint para agregar ha este 'empresas.json' .?

Gracias

**Comment by giansalex** [comment]
Hola @jose7847 , si hay un [parametro](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/giansalex/lycet/master/public/swagger.yaml#/summary/getSummaryStatus) para agregar el ruc, seria asi `localhost:8080/api/v1/send?token=123456&ruc=20000000001`
![image](https://user-images.githubusercontent.com/14926587/102718208-f3659780-42b4-11eb-9822-2a8957eb9d5a.png)

**Comment by jose7847** [comment]
1. Con respecto al token seria el mismo para todas las empresas? o se agregaría en empresas.json?

2. Si emito un comprobante quebraría así?
 ` ./api/v1/invoice/send?token=123456&ruc=20000000001` empresa1
 ` ./api/v1/invoice/send?token=123456&ruc=20000000002` empresa2
 Los archivos que están en "data" el "cert.pem" y "logo.png" se elimina? ya que ahora estaría como multiempresa?? bueno le intente así pero me sale error ...
`Warning: openssl_sign(): supplied key param cannot be coerced into a private key`


Estoy empezando a utilizar **Lycet** 😃

**Comment by giansalex** [comment]
- En un inicio este repo solo se hizo para uso individual de cada empresa, luego se agrego `empresas.json` como soporte para multiples ruc, pero el `token` no cambio, y se mantiene siendo único para la aplicación.
- En `invoice/send` no es necesario agregar el parametro `ruc`, ya que lo toma desde el json de la factura, la ruta del certificado y logo ahora lo tomaría desde lo configurado en el json, tendrias que agregar en la carpeta /data el archivo `20000000001-cert.pem` igual para el logo.
```json
{
   "20000000001":{
      "SOL_USER":"20000000001MODDATOS",
      "SOL_PASS":"moddatos",
      "certificate":"20000000001-cert.pem",
      "logo":"20000000001-logo.png"
   }
}
```

**Comment by jonathan171** [comment]
hola buenas tardes quisiera saber porque la sunat me genera el siguiente error una vez que genero el xml y lo envio 

El documento electrónico ingresado ha sido alterado - Detalle: Incorrect reference digest value
el archivo xml se crea de forma correcta pero me salta ese error incluso con los ejemplos de json que se muestran en la documentacion

**Comment by erajuan** [comment]
@jonathan171 estás enviado un comprobante generado anteriormente?
