### ISSUE TITLE
Generación de QR

### ISSUE THREAD

**Issue by dikeii** [giansalex/lycet#340]
Buen día, estaba tratando de armar el pdf por fuera con mpdf, pero tengo la duda desde donde se genera el codigo qr, esta basado en el hash que retorna la sunat al realizar el ingreso del comprobante o tiene otra raiz?, gracias de antemano por esta grandiosa herramienta.

**Comment by dikeii** [comment]
Estuve buscando y ya vi que el contenido del qr es el siguiente

a)Número de RUC del emisor electrónico. 
b)Tipo de comprobante de pago electrónico
c)Numeración conformada por serie y número correlativo. 
d)Sumatoria IGV, de ser el caso.
e)Importe total de la venta, cesión en uso o servicio prestado.
f)Fecha de emisión.
g)Tipo de documento del adquirente o usuario, de ser el caso. 
h)Número de documento del adquirente o usuario, de ser el caso

**Comment by giansalex** [comment]
Hola @dikeii , así es.
