### ISSUE TITLE
Duplicado X509Certificate 

### ISSUE THREAD

**Issue by andraice** [giansalex/lycet#341]
Estimados:

Cuando genero el XML me envia varias veces la etiqueta X509Certificate.

Saludos

**Comment by giansalex** [comment]
Hola, revisa que solo tengas un sección `CERTIFICATE` en el archivo `cert.pem`
```
-----BEGIN CERTIFICATE-----
xxxxxxxx
xxxxxxxx
-----END CERTIFICATE-----
```
como en este [ejemplo](https://github.com/thegreenter/demo/blob/master/resources/cert.pem)

**Comment by andraice** [comment]
Tiene repetido 4 veces pero todos los certificados lo tienen igual o mi certificado esta mal?

**Comment by andraice** [comment]
Gracias, utilicé este manual https://github.com/thegreenter/xmldsig/blob/master/CONVERT.md y pude generarlo correctamente.

> Hola, revisa que solo tengas un sección `CERTIFICATE` en el archivo `cert.pem`
> 
> ```
> -----BEGIN CERTIFICATE-----
> xxxxxxxx
> xxxxxxxx
> -----END CERTIFICATE-----
> ```
> 
> como en este [ejemplo](https://github.com/thegreenter/demo/blob/master/resources/cert.pem)
