### ISSUE TITLE
CDR

### ISSUE THREAD

**Issue by henryvelas** [giansalex/lycet#343]
buenas tardes amigo, estoy buscando información de donde como podría obtener el CDR en el lycet pero no logro nada....podras apoyarme por favor???

esto es lo maximo que logro ver pero no estoy seguro sea

tengo entendido que es un archivo zip con un archivo que tiene estructura xml

  "sunatResponse": {
    "success": true,
    "cdrZip": "UEsDBBQAAgAIAIhZLlIAAAAAAgAAAAAAAAAGAAAAZHVtbXkvAwBQSwMEFAACAAgAiFkuUoykiifGAwAAmQsAAB0AAABSLTIwNjAyNTA4MDE0LTAzLUIwMDEtNjI2LnhtbLVW23LiOBB9n69wmYepmlpHsrmEuAxTELIZdjOECrDL5k2xhfHEllySuGS/fiXfTZwamKoFHuTW6dOt090yztdjFGp7zHhAyUA3r6CuYeJSLyD+QF8tfzf6+tfhJwcxexTHYeAiIYFPmMeUcKxJZ8JtxAb6jhGbIh5wm6AIc5vH2A02Gd7evYQ2d7c4QvaRe01UhqVnbPgoLqS7pVFEyd1RYKKOIR8lJSaCl6Tui/tLpGMJdxsJ0a8RjnyfYR8J3ETq8YG+FSK2ATgcDleH9hVlPrAghADeAInxeOC3cjSnKC7waSB+JbeUPXFUC4DJHoc0xkAfOlJaezV+KJTi702ppaIlkSsxdBaBT5DYsazmZ+Up+0a5YW9KNnT4SdOcW0QokfqEwb+JRt+x2FJPG4U+ZYHYRh/QmsCEitbAR9dwzQ5p/S3RSlClnw4S7iLDs0lhJ8/ViCjDLcaRwbeoa1oZ5RPeYCbHAWurp+lA15VRmpcMEb6hLOKpoWr6adiaRHlxPIPn2aehLyQ9RyBJCE4zdyaBj7m4UDGpSKuqU8HzFwp3eDiWUe6/Lx6Wq/tJ9Ah7/mt3MoHfrrePYL3+dtwfrA5cTxftVyD+8e5v1n9snvtz8KM760TP/dXt692Pu/l49rxcPy63ncXsmW2XYH0YDBxQjaLqA4oCyVYD9V6rdkTq8WXOgr2cPO0Vv2mfx1iguRxROd6Yic8aoULbxV9SmoqX8yd+SziddRfeTJBA6Up5pbMumWdy/D3NLU0ZfxpQMlT4T50TtinnO8wWmAUorFoU8eX0Fd+EK+Wd7aIXzC5nq3lXA+TpglIZUKhV6ijXzXcKeH/5gIYrSt7d9nQyNHsm7HU67fZ1D5oOyKzprkpnosS0oGUa0DTM9tLs2xDKXwYtIKXHMpACJZg6LLEnsPztVOfupNjaZg2eEJimbVq2eV0HZ9zItSv6ZGdRlsVqNlpWTlcAKXubIybeUluynHpSxuJ9U9BY0GzLr3XT7ZZE4GOvfCPtF+WQrCqZpDvgBAk+Sk6OaSBQWBxwJARyt1FSc7WvissICsvpTaLKO3bYOtFA2dJADU7gZ8HAqc7qERMPs/9HStAY4Am7ONhfELMHrS7sw7zPzojZEGJC3Z1SIW+8PJfiKWnKTEsZYizvd6Nn9fJ2LXdqrX1LPTkz9Z5ObAlqgrnLgjjJ7AFpYxrKi0UjMhFGtTzCb9oWaTzwqIZcHAvkoZSu6pwfq5p7eaJa27zLvdCrySEVK4gDaT+zID0Dlp9LSlKLApqLApr/WQ//A1BLAQIAABQAAgAIAIhZLlIAAAAAAgAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAABkdW1teS9QSwECAAAUAAIACACIWS5SjKSKJ8YDAACZCwAAHQAAAAAAAAABAAAAAAAmAAAAUi0yMDYwMjUwODAxNC0wMy1CMDAxLTYyNi54bWxQSwUGAAAAAAIAAgB/AAAAJwQAAAAA",
    "cdrResponse": {
      "id": "F001-626",
      "code": "0",
      "description": "La Factura numero F001-626, ha sido aceptada",
      "notes": []
    }
  }

**Comment by andraice** [comment]
Hola, 

Los caracteres de cdrZip tienes que guardarlo con .zip y listo, ese es el cdr en base64.

Saludos

**Comment by andraice** [comment]
Algo asi 

file_put_contents('./cdr/[un nombre del archivo].zip', base64_decode($json_response->sunatResponse->cdrZip));

**Comment by henryvelas** [comment]
muchas gracias amigo ya lo entendi...gracias
