### ISSUE TITLE
Attempted to load class "ZipArchive" from the global namespace. Did you forget a "use" statement?

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#346]
Tengo ahora mismo este error, adjunto una captura
![image](https://user-images.githubusercontent.com/28074529/106035173-cb323b00-60a1-11eb-89e2-c9e1f6250b5c.png)

Creo que es por una extensión, pero quisiera saber cual de ellas es la que tiene el inconveniente.

**Comment by giansalex** [comment]
@OD-n hola, en la ultima version del respositorio ya no se usa esa extension, la extension es `zip`

**Comment by OD-n** [comment]
Eso es todo, ya pude activar la extensión zip, era eso, muchas gracias, estaré revisando la nueva versión.
