### ISSUE TITLE
3244 - Debe consignar la informacion del tipo de transaccion del comprobante (FormaPago)

### ISSUE THREAD

**Issue by wilmerortiz** [giansalex/lycet#361]
¿Que parametro debo adicionar para solucionar esta observacion?
3244 - Debe consignar la informacion del tipo de transaccion del comprobante - INFO : 3244 (nodo: '/' valor: '')
Gracias.

**Comment by giansalex** [comment]
@wilmerortiz es algo que se agregado recientemente, tienes que actualizar el codigo.
Para el caso de forma de pago Contado
```json
{
    "formaPago": {
        "tipo": "Contado"
    },
}
```
Para forma de pago Credito
```json
    "formaPago": {
        "tipo": "Credito",
        "monto": 118.00
    },
    "cuotas": [
        {
            "monto": 50.00,
            "fechaPago": "2021-02-14T00:00:00-05:00"
        },
        {
            "monto": 68.00,
            "fechaPago": "2021-02-21T00:00:00-05:00"
        }
    ],
```

**Comment by wilmerortiz** [comment]
Gracias por tu pronta respuesta

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Giancarlos Salas<mailto:notifications@github.com>
Enviado: lunes, 8 de febrero de 2021 13:04
Para: giansalex/lycet<mailto:lycet@noreply.github.com>
CC: wilmerortiz<mailto:jhak_dy@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [giansalex/lycet] *Debe consignar la informacion del tipo de transaccion del comprobante (#361)


@wilmerortiz<https://github.com/wilmerortiz> es algo que se agregado recientemente, tienes que actualizar el codigo.
Para el caso de forma de pago Contado

{

    "formaPago": {

        "tipo": "Contado"

    },

}

Para forma de pago Credito

    "formaPago": {

        "tipo": "Credito",

        "monto": 118.00

    },

    "cuotas": [

        {

            "monto": 50.00,

            "fechaPago": "2021-02-14T00:00:00-05:00"

        },

        {

            "monto": 68.00,

            "fechaPago": "2021-02-21T00:00:00-05:00"

        }

    ],
