### ISSUE TITLE
Error al ejecutar la imagen-Docker

### ISSUE THREAD

**Issue by Recursero** [giansalex/lycet#363]
Hola Giancarlos:

He tratado de ejecutar Lycet en Docker pero hay un error. He realizado los pasos que están en el REadme. No sé si hay algo que esté obviando o se me ha pasado. 
También he pegado los dos archivos que se necesitan en data (cert.pem y logo.png).

--- Worker 5507 stderr ---

An exception was thrown by the bridge. Forcing restart of the worker. The exception was: Error: Class "Twig\Node\Expression\Test\DefinedTest" not found in /var/www/html/vendor/twig/twig/src/Node/Expression/Filter/DefaultFilter.php:37

Stack trace:

#0 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(560): Twig\Node\Expression\Filter\DefaultFilter->__construct()

#1 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(543): Twig\ExpressionParser->parseFilterExpressionRaw()

#2 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(401): Twig\ExpressionParser->parseFilterExpression()

#3 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(284): Twig\ExpressionParser->parsePostfixExpression()

#4 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(175): Twig\ExpressionParser->parsePrimaryExpression()

#5 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(70): Twig\ExpressionParser->getPrimary()

#6 /var/www/html/vendor/twig/twig/src/Parser.php(128): Twig\ExpressionParser->parseExpression()

#7 /var/www/html/vendor/twig/twig/src/TokenParser/IfTokenParser.php(41): Twig\Parser->subparse()

#8 /var/www/html/vendor/twig/twig/src/Parser.php(171): Twig\TokenParser\IfTokenParser->parse()

#9 /var/www/html/vendor/twig/twig/src/TokenParser/IfTokenParser.php(41): Twig\Parser->subparse()

#10 /var/www/html/vendor/twig/twig/src/Parser.php(171): Twig\TokenParser\IfTokenParser->parse()

#11 /var/www/html/vendor/twig/twig/src/TokenParser/ApplyTokenParser.php(42): Twig\Parser->subparse()

#12 /var/www/html/vendor/twig/twig/src/Parser.php(171): Twig\TokenParser\ApplyTokenParser->parse()

#13 /var/www/html/vendor/twig/twig/src/Parser.php(84): Twig\Parser->subparse()

#14 /var/www/html/vendor/twig/twig/src/Environment.php(479): Twig\Parser->parse()

#15 /var/www/html/vendor/twig/twig/src/Environment.php(507): Twig\Environment->parse()

#16 /var/www/html/vendor/twig/twig/src/Environment.php(348): Twig\Environment->compileSource()

#17 /var/www/html/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate()

#18 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load()

#19 /var/www/html/vendor/greenter/xml/src/Xml/Builder/TwigBuilder.php(51): Twig\Environment->render()

#20 /var/www/html/vendor/greenter/xml/src/Xml/Builder/InvoiceBuilder.php(49): Greenter\Xml\Builder\TwigBuilder->render()

#21 /var/www/html/vendor/greenter/lite/src/Greenter/Factory/FeFactory.php(155): Greenter\Xml\Builder\InvoiceBuilder->build()

#22 /var/www/html/vendor/greenter/lite/src/Greenter/Factory/FeFactory.php(127): Greenter\Factory\FeFactory->getXmlSigned()

#23 /var/www/html/vendor/greenter/lite/src/Greenter/See.php(165): Greenter\Factory\FeFactory->send()

#24 /var/www/html/src/Service/DocumentRequest.php(83): Greenter\See->send()

#25 /var/www/html/src/Controller/v1/InvoiceController.php(46): App\Service\DocumentRequest->send()

#26 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(157): App\Controller\v1\InvoiceController->send()

#27 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw()

#28 /var/www/html/vendor/symfony/http-kernel/Kernel.php(195): Symfony\Component\HttpKernel\HttpKernel->handle()

#29 /var/www/html/vendor/php-pm/httpkernel-adapter/src/Bridges/HttpKernel.php(87): Symfony\Component\HttpKernel\Kernel->handle()

#30 /var/www/html/vendor/php-pm/php-pm/src/ProcessSlave.php(454): PHPPM\Bridges\HttpKernel->handle()

#31 /var/www/html/vendor/php-pm/php-pm/src/ProcessSlave.php(418): PHPPM\ProcessSlave->handleRequest()

#32 /var/www/html/vendor/react/http/src/Io/MiddlewareRunner.php(49): PHPPM\ProcessSlave->onRequest()

#33 /var/www/html/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call()

#34 /var/www/html/vendor/react/http/src/Middleware/RequestBodyParserMiddleware.php(34): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}()

#35 /var/www/html/vendor/react/http/src/Io/MiddlewareRunner.php(59): React\Http\Middleware\RequestBodyParserMiddleware->__invoke()

#36 /var/www/html/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call()

#37 /var/www/html/vendor/react/http/src/Middleware/RequestBodyBufferMiddleware.php(56): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}()

#38 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): React\Http\Middleware\RequestBodyBufferMiddleware->React\Http\Middleware\{closure}()

#39 /var/www/html/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()

#40 /var/www/html/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()

#41 /var/www/html/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()

#42 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()

#43 /var/www/html/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done()

#44 /var/www/html/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()

#45 /var/www/html/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()

#46 /var/www/html/vendor/react/promise-stream/src/functions.php(75): React\Promise\Promise::React\Promise\{closure}()

#47 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Promise\Stream\{closure}()

#48 /var/www/html/vendor/react/http/src/Io/HttpBodyStream.php(80): Evenement\EventEmitter->emit()

#49 /var/www/html/vendor/react/http/src/Io/HttpBodyStream.php(179): React\Http\Io\HttpBodyStream->close()

#50 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\HttpBodyStream->handleEnd()

#51 /var/www/html/vendor/react/http/src/Io/LengthLimitedStream.php(87): Evenement\EventEmitter->emit()

#52 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\LengthLimitedStream->handleData()

#53 /var/www/html/vendor/react/http/src/Io/CloseProtectionStream.php(96): Evenement\EventEmitter->emit()

#54 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\CloseProtectionStream->handleData()

#55 /var/www/html/vendor/react/http/src/Io/RequestHeaderParser.php(100): Evenement\EventEmitter->emit()

#56 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\RequestHeaderParser->React\Http\Io\{closure}()

#57 /var/www/html/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()

#58 /var/www/html/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()

#59 /var/www/html/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit()

#60 /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData()

#61 /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()

#62 /var/www/html/vendor/php-pm/php-pm/src/ProcessSlave.php(377): React\EventLoop\StreamSelectLoop->run()

#63 /tmp/dbgJDghig(37): PHPPM\ProcessSlave->run()

#64 {main}

Script did not return a valid HTTP response. Maybe it has called exit() prematurely?

**Comment by giansalex** [comment]
Hola @Recursero , gracias por informarlo, se tenia un comando para elimina archivos no utilizados, pero con la ultima actualización de `greenter` ha quedado obsoleto.
Puedes actualizar el repositorio local a la ultima versión.
