### ISSUE TITLE
Docker: EndPoint /PDF y Modo producción multiempresas con errores

### ISSUE THREAD

**Issue by Recursero** [giansalex/lycet#364]
Hola Giancarlos:

Se solucionó el error anterior al momento de ejecutar el contenedor y enviar los datos de prueba al endpoint localhost:8000/api/v1/invoice/send/ -- todo ok hasta este punto.
He encontrado dos fallas luego de esto. El primero es cuando envías datos distintos al endpoint pdf/ siempre se imprime un mismo pdf a pesar de que los datos enviados son diferentes. El segundo es al momento de cambiar los datos el archivo .env para empezar los envíos en modo producción este continua enviando en modo prueba. ¿Hay que cambiar primero el Dockerfile y cambiar los endpoints de la sunat al modo producción en las variables ENV? Si hago esto, solo podría usar un solo usuario SOL a pesar de insertar el archivo empresas.json en la carpeta /data?

Gracias de antemano por tu respuesta y sobre todo por el estupendo trabajo que has realizado.

**Comment by Recursero** [comment]
![image](https://user-images.githubusercontent.com/45543343/108615475-8f557180-73d2-11eb-8b2d-af91197b3253.png)

**Comment by giansalex** [comment]
@Recursero sobre las url de produccion puedes configurarla al iniciar el contenedor, ejem:
```bash
docker run -d -p 8000:8000 --name lycet_app \
-e FE_URL=https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService \
-e SOL_USER=20000000001USER \
-e SOL_PASS=xxxxxx \
lycet 
```
el archivo `empresas.json` tiene prioridad sobre `SOL_USER` env, asi que podrias utilizarlo tambien.

**Comment by giansalex** [comment]
Sobre el PDF he notado que ocurre ese problema con [php-pm/php-pm](https://github.com/php-pm/php-pm), que se añadió hace un tiempo (anteriormente se usaba apache), en el caso actual symfony no regenera los servicios por cada petición, y esta parte del PDF no se adapta, se tendrá que hacer una actualización.

**Comment by giansalex** [comment]
@Recursero gracias por reportar esto, ya  puedes actualizar el repo.
