### ISSUE TITLE
Forma Pago, catálogo SUNAT

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#371]
Buen día, actualmente se debe consignar el medio de pago, pude ver en otra pregunta que como se puede enviar si es en caso de contado o crédito, como interviene ahí catálogos de SUNAT.
Hay una tabla, envío una captura para ver si es necesario enviar el código que se tiene ahí.
![image](https://user-images.githubusercontent.com/28074529/110271263-a204a480-7f95-11eb-9ba3-70a1ce398c81.png)

**Comment by giansalex** [comment]
Hola @OD-n , estas confundiendo el medio de pago con la forma de pago(contado, crédito), esta ultima es la que será obligatorio en abril.

**Comment by OD-n** [comment]
@giansalex muchas gracias por aclarármelo y responder tan pronto. Lo entendí perfectamente.
