### ISSUE TITLE
No funciona la imagen docker

### ISSUE THREAD

**Issue by polchis** [giansalex/lycet#383]
Buenas tardes,
No logro levantar el lycet en docker  en mi tterminal se muestra en letras rojas todo esto 
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 59 installs, 0 updates, 0 removals
  - Downloading symfony/flex (v1.12.2)
  - Downloading dasprid/enum (1.0.3)
  - Downloading doctrine/lexer (1.2.1)
  - Downloading doctrine/annotations (1.12.1)
  - Downloading doctrine/instantiator (1.4.0)
  - Downloading mikehaertl/php-tmpfile (1.2.1)
  - Downloading mikehaertl/php-shellcommand (1.6.4)
  - Downloading mikehaertl/phpwkhtmltopdf (2.5.0)
  - Downloading greenter/core (v4.3.1)
  - Downloading greenter/htmltopdf (v4.3.1)
  - Downloading greenter/xmldsig (v5.0.3)
  - Downloading symfony/polyfill-mbstring (v1.22.1)
  - Downloading twig/twig (v3.3.0)
  - Downloading greenter/xml (v4.3.1)
  - Downloading symfony/finder (v5.2.4)
  - Downloading psr/http-message (1.0.1)
  - Downloading paragonie/random_compat (v9.99.100)
  - Downloading nelexa/zip (3.3.3)
  - Downloading greenter/ws (v4.3.1)
  - Downloading greenter/lite (v4.3.1)
  - Downloading bacon/bacon-qr-code (2.0.3)
  - Downloading greenter/report (v4.3.1)
  - Downloading symfony/polyfill-php80 (v1.22.1)
  - Downloading symfony/deprecation-contracts (v2.2.0)
  - Downloading symfony/routing (v5.2.4)
  - Downloading symfony/polyfill-php73 (v1.22.1)
  - Downloading symfony/http-foundation (v5.2.4)
  - Downloading symfony/http-client-contracts (v2.3.1)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher-contracts (v2.2.0)
  - Downloading symfony/event-dispatcher (v5.2.4)
  - Downloading symfony/var-dumper (v5.2.6)
  - Downloading psr/log (1.1.3)
  - Downloading symfony/error-handler (v5.2.6)
  - Downloading symfony/http-kernel (v5.2.6)
  - Downloading symfony/filesystem (v5.2.6)
  - Downloading psr/container (1.1.1)
  - Downloading symfony/service-contracts (v2.2.0)
  - Downloading symfony/dependency-injection (v5.2.6)
  - Downloading symfony/config (v5.2.4)
  - Downloading symfony/var-exporter (v5.2.4)
  - Downloading psr/cache (1.0.1)
  - Downloading symfony/cache-contracts (v2.2.0)
  - Downloading symfony/cache (v5.2.4)
  - Downloading symfony/framework-bundle (v5.2.5)
  - Downloading phpstan/phpdoc-parser (0.4.14)
  - Downloading jms/metadata (2.5.0)
  - Downloading jms/serializer (3.12.2)
  - Downloading jms/serializer-bundle (3.9.1)
  - Downloading nelmio/cors-bundle (2.1.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.22.1)
  - Downloading symfony/polyfill-intl-grapheme (v1.22.1)
  - Downloading symfony/string (v5.2.4)
  - Downloading symfony/console (v5.2.5)
  - Downloading symfony/dotenv (v5.2.4)
  - Downloading monolog/monolog (2.2.0)
  - Downloading symfony/monolog-bridge (v5.2.5)
  - Downloading symfony/monolog-bundle (v3.7.0)
  - Downloading symfony/yaml (v5.2.5)
  - Installing symfony/flex (v1.12.2): Extracting archive
  - Installing dasprid/enum (1.0.3): Extracting archive
  - Installing doctrine/lexer (1.2.1): Extracting archive
  - Installing doctrine/annotations (1.12.1): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing mikehaertl/php-tmpfile (1.2.1): Extracting archive
  - Installing mikehaertl/php-shellcommand (1.6.4): Extracting archive
  - Installing mikehaertl/phpwkhtmltopdf (2.5.0): Extracting archive
  - Installing greenter/core (v4.3.1): Extracting archive
  - Installing greenter/htmltopdf (v4.3.1): Extracting archive
  - Installing greenter/xmldsig (v5.0.3): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.22.1): Extracting archive
  - Installing twig/twig (v3.3.0): Extracting archive
  - Installing greenter/xml (v4.3.1): Extracting archive
  - Installing symfony/finder (v5.2.4): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing nelexa/zip (3.3.3): Extracting archive
  - Installing greenter/ws (v4.3.1): Extracting archive
  - Installing greenter/lite (v4.3.1): Extracting archive
  - Installing bacon/bacon-qr-code (2.0.3): Extracting archive
  - Installing greenter/report (v4.3.1): Extracting archive
  - Installing symfony/polyfill-php80 (v1.22.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/routing (v5.2.4): Extracting archive
  - Installing symfony/polyfill-php73 (v1.22.1): Extracting archive
  - Installing symfony/http-foundation (v5.2.4): Extracting archive
  - Installing symfony/http-client-contracts (v2.3.1): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v2.2.0): Extracting archive
  - Installing symfony/event-dispatcher (v5.2.4): Extracting archive
  - Installing symfony/var-dumper (v5.2.6): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing symfony/error-handler (v5.2.6): Extracting archive
  - Installing symfony/http-kernel (v5.2.6): Extracting archive
  - Installing symfony/filesystem (v5.2.6): Extracting archive
  - Installing psr/container (1.1.1): Extracting archive
  - Installing symfony/service-contracts (v2.2.0): Extracting archive
  - Installing symfony/dependency-injection (v5.2.6): Extracting archive
  - Installing symfony/config (v5.2.4): Extracting archive
  - Installing symfony/var-exporter (v5.2.4): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing symfony/cache-contracts (v2.2.0): Extracting archive
  - Installing symfony/cache (v5.2.4): Extracting archive
  - Installing symfony/framework-bundle (v5.2.5): Extracting archive
  - Installing phpstan/phpdoc-parser (0.4.14): Extracting archive
  - Installing jms/metadata (2.5.0): Extracting archive
  - Installing jms/serializer (3.12.2): Extracting archive
  - Installing jms/serializer-bundle (3.9.1): Extracting archive
  - Installing nelmio/cors-bundle (2.1.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.22.1): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.22.1): Extracting archive
  - Installing symfony/string (v5.2.4): Extracting archive
  - Installing symfony/console (v5.2.5): Extracting archive
  - Installing symfony/dotenv (v5.2.4): Extracting archive
  - Installing monolog/monolog (2.2.0): Extracting archive
  - Installing symfony/monolog-bridge (v5.2.5): Extracting archive
  - Installing symfony/monolog-bundle (v3.7.0): Extracting archive
  - Installing symfony/yaml (v5.2.5): Extracting archive
36 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Using version ^2.2 for php-pm/php-pm
Using version ^2.0 for php-pm/httpkernel-adapter
./composer.json has been updated
Running composer update php-pm/php-pm php-pm/httpkernel-adapter
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.2.*"
Updating dependencies
Lock file operations: 18 installs, 0 updates, 0 removals
  - Locking evenement/evenement (v3.0.1)
  - Locking guzzlehttp/psr7 (1.8.1)
  - Locking php-pm/httpkernel-adapter (2.0.6)
  - Locking php-pm/php-pm (2.2.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking react/cache (v1.1.1)
  - Locking react/child-process (v0.6.2)
  - Locking react/dns (v1.5.0)
  - Locking react/event-loop (v1.1.1)
  - Locking react/http (v1.2.0)
  - Locking react/promise (v2.8.0)
  - Locking react/promise-stream (v1.2.0)
  - Locking react/promise-timer (v1.6.0)
  - Locking react/socket (v1.6.0)
  - Locking react/stream (v1.1.1)
  - Locking ringcentral/psr7 (1.3.0)
  - Locking symfony/process (v5.2.4)
Writing lock file
Installing dependencies from lock file
Package operations: 18 installs, 0 updates, 0 removals
  - Downloading symfony/process (v5.2.4)
  - Downloading ringcentral/psr7 (1.3.0)
  - Downloading react/event-loop (v1.1.1)
  - Downloading evenement/evenement (v3.0.1)
  - Downloading react/stream (v1.1.1)
  - Downloading react/promise (v2.8.0)
  - Downloading react/promise-timer (v1.6.0)
  - Downloading react/cache (v1.1.1)
  - Downloading react/dns (v1.5.0)
  - Downloading react/socket (v1.6.0)
  - Downloading react/promise-stream (v1.2.0)
  - Downloading react/http (v1.2.0)
  - Downloading react/child-process (v0.6.2)
  - Downloading psr/http-server-handler (1.0.1)
  - Downloading php-pm/php-pm (2.2.1)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading guzzlehttp/psr7 (1.8.1)
  - Downloading php-pm/httpkernel-adapter (2.0.6)
  - Installing symfony/process (v5.2.4): Extracting archive
  - Installing ringcentral/psr7 (1.3.0): Extracting archive
  - Installing react/event-loop (v1.1.1): Extracting archive
  - Installing evenement/evenement (v3.0.1): Extracting archive
  - Installing react/stream (v1.1.1): Extracting archive
  - Installing react/promise (v2.8.0): Extracting archive
  - Installing react/promise-timer (v1.6.0): Extracting archive
  - Installing react/cache (v1.1.1): Extracting archive
  - Installing react/dns (v1.5.0): Extracting archive
  - Installing react/socket (v1.6.0): Extracting archive
  - Installing react/promise-stream (v1.2.0): Extracting archive
  - Installing react/http (v1.2.0): Extracting archive
  - Installing react/child-process (v0.6.2): Extracting archive
  - Installing psr/http-server-handler (1.0.1): Extracting archive
  - Installing php-pm/php-pm (2.2.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing guzzlehttp/psr7 (1.8.1): Extracting archive
  - Installing php-pm/httpkernel-adapter (2.0.6): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
42 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Nothing to unpack

Y al termina la instalacion sale  esto tambien en letras  rojas
In EnvVarProcessor.php line 171:
                                                      
  Environment variable not found: "TRUSTED_PROXIES".  
                                                      
x-special/nautilus-clipboard
copy
file:///home/losung/Im%C3%A1genes/Captura%20de%20pantalla%20de%202021-04-06%2017-47-04.png

**Comment by giansalex** [comment]
Hola, falto actualizar ese archivo con un ultimo cambio que hubo, ya se subió la actualización y puedes probar.
