### ISSUE TITLE
Problema para obtener el PDF - wkhtmltopdf

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#386]
Al realizar la petición de pdf, obtengo el siguiente error:
`<!-- sh: /home/.../wkhtmltopdf: Permission denied (500 Internal Server Error) -->`

Estoy usándolo en un servidor compartido, leí que debería dar permisos de ejecución, como debería hacerlo si es posible en un servidor compartido?

**Comment by giansalex** [comment]
El hosting debe tener un administrador de archivos, alli debe aparecer un menu al dar click derecho sobre el archivo, y tener la opcion de propiedades o permisos, alli debes poder darle permiso de ejecucion.
