### ISSUE TITLE
Al enviar los datos a la API me sale error 403

### ISSUE THREAD

**Issue by OBSK** [giansalex/lycet#4]
Tengo un problema, al enviar los datos al API me retorna el siguiente error: 
Failed to load http://localhost:8000/api/v1/invoice/send: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403.
y en el log:
[info] Matched route "app_v1_invoice_send"
[critical] uncaught Exception: this action needs a valid token!

**Comment by giansalex** [comment]
Necesitas enviar el token de seguridad, puedes revisar la api en [swagger](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/giansalex/lycet/master/public/swagger.yaml)

**Comment by OBSK** [comment]
giansalex, muchas gracias por la respuesta, a ignorancia mía no leí muy bien la documentación. Acabo de enviar una petición axios con el token de seguridad, pero me retorna: 
[info] User Deprecated: The "Symfony\Component\HttpKernel\EventListener\SaveSessionListener" class is deprecated since Symfony 4.1, use AbstractSessionListener instead.
[info] Matched route "app_v1_invoice_send".
[critical] Uncaught Exception: The "serializer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
[error 500].
Muchas gracias

**Comment by OBSK** [comment]
¿hay alguna solución?

**Comment by giansalex** [comment]
Puedes intentar borrar las carpetas `vendor` y `var`, luego volver a instalar los paquetes.

**Comment by OBSK** [comment]
Acabo de hacerlo, también volví a clonar el repositorio y instalar los paquetes.Sigo obteniendo el mismo error. Estoy enviando los datos: 
```
axios.post('http://localhost:8000/api/v1/invoice/send', args, {
params: {
token: '123456'
}
}).then(res => console.log(res)).catch(err => console.log(err));
```

#¿Hay algo que estoy obviando?
Gracias. Saludos desde Tarapoto :+1: .

**Comment by giansalex** [comment]
Hola @OBSK , el problema esta corregido.

**Comment by eilsongithub** [comment]
Estimado  giansalex  por brindar este código gratuito. Soy nuevo en este tema, ojalá me puedan ayudar. 
Estoy haciendo pruebas desde swagger sin embargo no logro hacer alguna con éxito

Obtengo este error
TypeError: Failed to fetch
y en consola:

Failed to load http://localhost/lycet/public/api/v1/invoice/send?token=123456: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://petstore.swagger.io, *', but only one is allowed. Origin 'http://petstore.swagger.io' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

activando el complento CORS de chrome 
obtengo
500Undocumented | Error: Internal Server Error
y en consola 
POST http://localhost/lycet/public/api/v1/invoice/send?token=123456 500 (Internal Server Error)

**Comment by eilsongithub** [comment]
Gracias por tu tiempo. tal-vez no estoy usando bien la api. si me reprochas lo comprendo. adjunto un pantallazo del postman.
![sin titulo](https://user-images.githubusercontent.com/44086967/46879334-5f156580-ce0b-11e8-86bc-4ce292011dd8.png)

**Comment by giansalex** [comment]
la ruta seria `/api/v1/invoice/send`

**Comment by eilsongithub** [comment]
Obtengo
could not decode json syntax error - malformed json

![postman 4](https://user-images.githubusercontent.com/44086967/46895605-d6b0b800-ce3e-11e8-9923-23f618856435.JPG)
![postman 5](https://user-images.githubusercontent.com/44086967/46895620-dfa18980-ce3e-11e8-9f90-7ad4730970f2.JPG)

**Comment by giansalex** [comment]
Alli mismo en el **postman** te esta marcando el error en la **fecha de emision**

**Comment by eilsongithub** [comment]
Si gracias ... estoy buscando el formato correcto....

**Comment by eilsongithub** [comment]
Al fin pase a esto
openssl_sign(): suplied key param cannot be coercend into a private key

![postman 6](https://user-images.githubusercontent.com/44086967/46897432-2e9fec80-ce48-11e8-9eb6-7fca1ad71400.JPG)

**Comment by giansalex** [comment]
el certificado que estas usando talvez es `.cer` (clave publica), necesitas el .pem que incluya la clave privada y publica.
Si tienes el .pfx puedes convertirlo a .pem con este [ejemplo](https://github.com/giansalex/xmldsig/blob/master/CONVERT.md)

**Comment by eilsongithub** [comment]
Gracias por tu paciencia, lo haré ...

**Comment by eilsongithub** [comment]
Creo que ya es una respueta de SUNAT... 
![postman 7](https://user-images.githubusercontent.com/44086967/46898178-0ebef780-ce4d-11e8-8937-ee13c982764c.JPG)
![postman 8](https://user-images.githubusercontent.com/44086967/46898199-36ae5b00-ce4d-11e8-8f1e-20d6d2a76a05.JPG)

**Comment by giansalex** [comment]
revisa la unidad de medida que estas usando, debe estar en la lista de Unidades Internacionales, si puedes sube el json que envias al API.

**Comment by eilsongithub** [comment]
Ok, revisaré.

Claro que si: 

{
  "tipoDoc": "03",
  "serie": "B001",
  "correlativo": "1",
  "fechaEmision": "2017-05-11T00:00:00+08:00",
  "client": {
    "tipoDoc": "1",
    "numDoc": "20203030",
    "rznSocial": "PERSON 1",
    "address": {
      "ubigueo": "060101",
      "codigoPais": "51",
      "departamento": "CAJAMARCA",
      "provincia": "CAJAMARCA",
      "distrito": "CAJAMARCA",
      "urbanizacion": "CRUZ BLANCA",
      "direccion": "AV. INDEPENDENCIA"
    }
  },
  "company": {
    "ruc": "20123456789",
    "razonSocial": "GREENTER S.A.C",
    "nombreComercial": "GREENTER",
    "address": {
      "ubigueo": "060101",
      "codigoPais": "51",
      "departamento": "LIMA",
      "provincia": "LIMA",
      "distrito": "LIMA",
      "urbanizacion": "LIMA",
      "direccion": "JR. NIQUEL MZA. F LOTE. 3 URB.  INDUSTRIAL INFANTAS - LIMA - LIMA -PERU"
    }
  },
  "tipoMoneda": "PEN",
  "sumOtrosCargos": 0,
  "mtoOperGravadas": 200,
  "mtoOperInafectas": 0,
  "mtoOperExoneradas": 0,
  "mtoIGV": 36,
  "mtoISC": 2,
  "mtoOtrosTributos": 0,
  "mtoImpVenta": 236,
  "details": [
    {
      "unidad": "NIU",
      "cantidad": 2,
      "codProducto": "C023",
      "codProdSunat": "C023",
      "descripcion": "PRODUCTO 1",
      "mtoValorUnitario": 50,
      "descuento": 0,
      "igv": 18,
      "tipAfeIgv": "10",
      "isc": 3,
      "tipSisIsc": "3",
      "mtoPrecioUnitario": 56,
      "mtoValorVenta": 100,
      "mtoValorGratuito": 12
    }
  ],
  "legends": [
    {
      "code": "1000",
      "value": "SON DOSCIENTOS TREINTA Y SEIS CON 00/100 SOLES"
    }
  ],
  "guias": [
    {
      "tipoDoc": "02",
      "nroDoc": "F001-21"
    }
  ],
  "relDocs": [
    {
      "tipoDoc": "02",
      "nroDoc": "F001-21"
    }
  ],
  "name": "string",
  "tipoOperacion": "string",
  "sumDsctoGlobal": 0,
  "mtoDescuentos": 0,
  "mtoOperGratuitas": 0,
  "totalAnticipos": 0,
  "perception": {
    "codReg": "01",
    "mtoBase": 0,
    "mto": 0,
    "mtoTotal": 0
  },
  "compra": "string",
  "anticipos": [
    {
      "tipoDocRel": "02",
      "nroDocRel": "F001-21",
      "total": 0
    }
  ],
  "detraccion": {
    "percent": 0,
    "mount": 0,
    "valueRef": 0
  },
  "guiaEmbebida": {
    "llegada": {
      "ubigueo": "060606",
      "direccion": "jr"
    },
    "partida": {
      "ubigueo": "060101",
      "direccion": "av"
    },
    "transportista": {
      "tipoDoc": "1",
      "numDoc": "429045603",
      "rznSocial": "WILSON",
      "address": {
        "ubigueo": "06000",
        "codigoPais": "",
        "departamento": "",
        "provincia": "",
        "distrito": "",
        "urbanizacion": "",
        "direccion": "Av. Independencia"
      }
    },
    "nroLicencia": "",
    "transpPlaca": "",
    "transpCodeAuth": "",
    "transpMarca": "",
    "modTraslado": "",
    "pesoBruto": 0,
    "undPesoBruto": ""
  }
}

**Comment by giansalex** [comment]
prueba enviando la muestra de abajo, puedes editar con tus datos luego ir agregando otros campos como detraccion, anticipos, segun vayas necesitandolo.
```json
  {
    "tipoDoc": "01",
    "serie": "F001",
    "correlativo": "111",
    "fechaEmision": "2018-01-20T12:34:00+01:00",
    "client": {
      "tipoDoc": "6",
      "numDoc": "20546687668",
      "rznSocial": "COMPANY SAC"
    },
    "company": {
      "ruc": "20123456789",
      "razonSocial": "LYCET COMPANY SAC",
      "nombreComercial": "COMPANY ",
      "address": {
        "ubigueo": "150101",
        "codigoPais": "PE",
        "departamento": "LIMA",
        "provincia": "LIMA",
        "distrito": "LIMA",
        "urbanizacion": "-",
        "direccion": "AV ITALIA"
      }
    },
    "tipoMoneda": "PEN",
    "mtoOperGravadas": 100,
    "mtoOperInafectas": 0,
    "mtoOperExoneradas": 0,
    "mtoIGV": 18,
    "mtoImpVenta": 118,
    "details": [
      {
        "unidad": "NIU",
        "cantidad": 12,
        "codProducto": "string",
        "descripcion": "PRODUCTO 1",
        "mtoValorUnitario": 100,
        "igv": 18,
        "tipAfeIgv": "10",
        "mtoPrecioUnitario": 118,
        "mtoValorVenta": 100
      }
    ],
    "legends": [
      {
        "code": "1000",
        "value": "SON CIEN CON 00/100 SOLES"
      }
    ]
  }
```

**Comment by eilsongithub** [comment]
Mil gracias ... ya puedo empezar ... a trabajar ... 

![image](https://user-images.githubusercontent.com/44086967/46907703-3c9f4d00-cedc-11e8-8907-22eed91c7a4e.png)

Te mantendré al tanto cuando llegue hacerlo en produccion
