### ISSUE TITLE
Error al enviar linea con Precio = "0"

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#40]
Al enviar una linea de factura con precio "0" me aparece el siguiente error...
**Debe existir el tag cac:AlternativeConditionPrice/cbc:PriceAmount - Detalle: xxx.xxx.xxx value='ticket: 1551969141757 error: Error en la linea: 2: 2028 (nodo: "/" valor: "")'**

Como puedo modificar el Json para poder enviar lo que me pide, o que puedo hacer

**Comment by giansalex** [comment]
Hola @OD-n, si el detalle es gratuito tienes que enviar el precio en el campo `mtoValorGratuito`

**Comment by OD-n** [comment]
Gracias @giansalex , el problema sigue apareciendo... me sale porque tengo 2 lineas:
En una el neto, el descuento y el total es "0",
Entonces `mtoValorGratuito` se debe añadir como "0"... no se si está bien el Json que a continuacion estoy generando...  Gracias de antemano

  {
    "tipoMoneda": "PEN", 
     "mtoOperGravadas": 168.64, 
            "mtoOperInafectas": 0,
            "mtoOperExoneradas": 0,  "mtoIGV": 30.36, 
    "totalImpuestos": 30.36,
    "valorVenta": 168.64,
    "mtoImpVenta": 199,
    "details": [       {
        "item": 1,
        "unidad":   "NIU",
        "cantidad": 1,
        "descripcion":  "AUDIFONOS",
        "mtoValorUnitario": 142.92,
        "mtoValorVenta": 168.64,
        "mtoValorVentaparapdf": 199,
        "mtoBaseIgv": 168.64,
        "porcentajeIgv":  18,
        "igv": 30.36,
        "tipAfeIgv": "10",
        "totalImpuestos": 30.36,
        "mtoPrecioUnitario": 168.64
        },      {
        **"item": 2,
        "unidad":   "NIU",
        "cantidad": 1,
        "descripcion":  "AUDIFONOS gratis",
        "mtoValorUnitario": 0,
        "mtoValorVenta": 0,
        "mtoValorVentaparapdf": 0,
        "mtoBaseIgv": 0,
        "porcentajeIgv":  18,
        "igv": 0,
        "tipAfeIgv": "10",
        "totalImpuestos": 0,
        "mtoPrecioUnitario": 0, 
                "mtoValorGratuito": 0
        }**
    ],
    "legends": [
      {
        "code": "1000",
        "value":  "CIENTO NOVENTA Y  NUEVE   con 0/100"
      }
    ]
  }

**Comment by giansalex** [comment]
Si el detalle es gratuito, el campo de tipo afectacion igv (`tipAfeIgv`) debe ser un valor diferente a `10,20,30,40`, puedes revisar el catalogo de sunat y elegir el correcto

**Comment by OD-n** [comment]
Muchas gracias @giansalex ... **todo correcto**
