### ISSUE TITLE
Docker: Resumen diario Error de nombre archivo

### ISSUE THREAD

**Issue by erajuan** [giansalex/lycet#407]
En docker funciona correctamente pero despues de un día sale el siguiente error
`El nombre del archivo ZIP es incorrecto - Detalle: xxx.xxx.xxx value='ticket:  error: Error de nombre archivo \"RUC---1.zip codigo cpe: -- no es un cpe valido'`

Requiere que se vuelva a crear de nuevo para que funcione correctamente.

**Comment by giansalex** [comment]
Esto parece un error relacionado a este [issue](https://github.com/giansalex/lycet/issues/364#issuecomment-782890011) .

**Comment by erajuan** [comment]
Si parece el mismo error, pero estoy usando la ultima version. Enviando a producción

**Comment by giansalex** [comment]
@erajuan usas este formato para las fechas?
```json
{
  "fecGeneracion": "2019-03-12T08:36:21-05:00",
  "fecResumen": "2019-03-13T23:44:35-05:00",
}
```

**Comment by erajuan** [comment]
Si uso ese formato.
Pero cuando se reinicio o vuelvo a crear el contenedor todo ok.
Pero para el día siguiente. Ya fue, error en cada envio!

**Comment by giansalex** [comment]
@erajuan tengo un instancia ejecutándose desde ayer, he enviado varias veces con diferentes fecha y no se reproduce ese error

**Comment by giansalex** [comment]
Probé este caso de nuevo, y no se presenta el problema.  Subi la imagen al repositorio https://github.com/giansalex/lycet/pkgs/container/lycet
