### ISSUE TITLE
Modelo JSON Guía de Remisión

### ISSUE THREAD

**Issue by eilsongithub** [giansalex/lycet#42]
Estimados srs. buenas tardes, ojalá me puedan ayudar con un modelo de json ubl 2.1 para guia de remisión ... estoy haciendo envíos y no tengo éxito ... tengo el error 500 internal server error. 

Este es el json que estoy enviando:

{
	"tipoDoc":"09",
	"serie":"T001",
	"correlativo":"213123",
	"observacion":"NOTA GUIA",
	"fechaEmision":
	{
		"date":"2019-03-16T15:51:01+00:00", 
		"timezone_type":3,
		"timezone":"UTC"
	},
	"company":
	{
		"ruc":"20123456789",
		"razonSocial":"GREENTER S.A.C",
		"nombreComercial":"GREENTER",
		"address":
		{
			"ubigueo":"060101",
			"codigoPais":"PE",
			"departamento":"cajamarca",
			"provincia":"cajamarca",
			"distrito":"cajamarca",
			"urbanizacion":"null",
			"direccion":"AV LOS GERANIOS 321 - LIMA - LIMA - PERU"
		},
		"email":"null",
		"telephone":"null"
	},
	"destinatario":
	{
		"tipoDoc":"6",
		"numDoc":"20000000002",
		"rznSocial":"EMPRESA 1",
		"address":"null",
		"email":"null",
		"telephone":"null"},
		"tercero":
		{
			"tipoDoc":"6",
			"numDoc":"20000000003",
			"rznSocial":"EMPRESA SA",
			"address":"null",
			"email":"null",
			"telephone":"null"
		},
		"envio":
		{
			"codTraslado":"01",
			"desTraslado":"VENTA",
			"indTransbordo":false,
			"pesoTotal":12.5,
			"undPesoTotal":"KGM",
			"numBultos":2,
			"modTraslado":"01",
			"fecTraslado":
			{
				"date":"2019-03-16 15:51:01.046040",
				"timezone_type":3,
				"timezone":"UTC"
			},
			"numContenedor":"XD-2232",
			"codPuerto":"123",
			"transportista":
			{
				"tipoDoc":"6",
				"numDoc":"20000000002",
				"rznSocial":"TRANSPORTES S.A.C",
				"placa":"ABI-453",
				"choferTipoDoc":"1",
				"choferDoc":"40003344"
			},
			"llegada":
			{
				"ubigueo":"150101",
				"direccion":"AV LIMA"
			},
			"partida":
			{
				"ubigueo":"150203",
				"direccion":"AV ITALIA"
			}
		},
		"docBaja":
		{
			"tipoDoc":"09",
			"nroDoc":"T001-00001"
		},
		"relDoc":
		{
			"tipoDoc":"02",
			"nroDoc":"213123"
		},
		"details":[
		{
			"codigo":"PROD1",
			"descripcion":"PROD 1",
			"unidad":"ZZ",
			"cantidad":2,
			"codProdSunat":"P001"
		}
		]
}

**Comment by giansalex** [comment]
Hola, puedes guiarte de los campos que se usan en este [ejemplo](https://github.com/giansalex/greenter-sample/blob/master/examples/guia-remision.php).

**Comment by eilsongithub** [comment]
Si ...son los mismos datos ... 
¿el errror 500 internal server error puede ser porque no está bien el json u otro puede ser el motivo?

**Comment by giansalex** [comment]
El campo `fechaEmision, fecTraslado` y cualquier otra fecha, no es un objeto, es una cadena, el mismo formato que se usa para la fecha de emsion, que envias en una factura.

**Comment by eilsongithub** [comment]
Si efectivamente, fue ese el inconveniente ... 
Gracias
