### ISSUE TITLE
Error al enviar JSON - Comunicacion de Baja

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#43]
Buenas, estoy tratando de realizar el documento JSON de la comunicación de bajas, es el siguiente, pero tengo problemas porque recibo el error 

> 500 internal server

```json
{
	"correlativo":"111",
	"fecGeneracion":"2019-02-16T15:51:01+00:00",
	"fecComunicacion":"2019-03-16T15:51:01+00:00",
	"company":
	{
		"ruc":"20123456789",
		"razonSocial":"GREENTER S.A.C",
		"nombreComercial":"GREENTER",
		"address":
		{
			"codigoPais":"PE",
			"direccion":"AV LOS GERANIOS 321 - LIMA - LIMA - PERU"
			
		}
	},
	"details":
	[
		{
			"tipoDoc":"01",
			"serie":"F001",
			"correlativo":"02132132",
			"desMotivoBaja":"ERROR DE SISTEMA"
		},
		{
			"tipoDoc":"07",
			"serie":"FC01",
			"correlativo":"222",
			"desMotivoBaja":"ERROR DE RUC"
			
		}
		]
}
```
Si alguien puede ayudarme sería de gran ayuda, gracias.

**Comment by giansalex** [comment]
Podrias revisar el log, solo alli tienes error, o enviando otros comprobantes?

**Comment by OD-n** [comment]
Revisando el log de hoy tengo esto:
```
[19-Mar-2019 22:45:02 UTC] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getCdrZip" of class "Greenter\Model\Response\SummaryResult". in /home/prueb/pruebas/src/Service/DocumentRequest.php:96
Stack trace:
#0 /home/prueb/pruebas/src/Controller/v1/VoidedController.php(47): App\Service\DocumentRequest->send()
#1 /home/prueb/pruebas/vendor/symfony/http-kernel/HttpKernel.php(150): App\Controller\v1\VoidedController->send()
#2 /home/prueb/pruebas/vendor/symfony/http-kernel/HttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#3 /home/prueb/pruebas/vendor/symfony/http-kernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#4 /home/prueb/pruebas/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#5 {main in /home/prueb/pruebas/src/Service/DocumentRequest.php on line 96
```

**Comment by giansalex** [comment]
Podrias actualizar el repostorio, o tal vez se realizo alguna modificacion.
> Recordar que actualmente se requiere php 7.2

**Comment by OD-n** [comment]
Okay... muchas gracias, voy a hacerlo y comentaré que es lo que pasó

**Comment by giansalex** [comment]
Hola @OD-n , pudiste solucionarlo?

**Comment by Ajahuanex** [comment]
Hola, Giancarlo. gracias por la respuesta, si funcionó Lycet, ahora estoy probando el API. de consult-peru no logro hacer funcionar la parte de RENIEC.



Enviado desde mi Redmi 4X
El Giancarlos Salas <notifications@github.com>, 3 abr. 2019 4:27 p. m. escribió:

Hola @OD-n<https://github.com/OD-n> , pudiste solucionarlo?

**Comment by Ajahuanex** [comment]
Si gracias, voy avanzando poco a poco.



Enviado desde mi Redmi 4X
El Giancarlos Salas <notifications@github.com>, 3 abr. 2019 4:27 p. m. escribió:

Hola @OD-n<https://github.com/OD-n> , pudiste solucionarlo?
