### ISSUE TITLE
donde se guarda el PDF y XML?

### ISSUE THREAD

**Issue by yersey20037** [giansalex/lycet#434]
Hola Giansalex obtengo este mensaje al llamar a la api del pdf desde Postman

Failed without error message: wkhtmltopdf &quot;--no-outline&quot; &quot;--no-outline&quot; &quot;--print-media-type&quot; &quot;C:\Users\Usuario\AppData\Local\Temp\tmpC6FF.tmp.html&quot; &quot;C:\Users\Usuario\AppData\Local\Temp\tmpC710.tmp.pdf&quot; (Exit code: 1) (500 Internal Server Error)

porfavor podrias indicarme cual es el error y donde es que se guarda el PDF o donde tengo que cambiarlo?
Muchas gracias

**Comment by yersey20037** [comment]
si estaba revisando eso lo instale y lo configure en el ENV y ya lo puedo descargar en el POSTMAN
mi conslta quedaria en si se puede guardar  automaticamente el archivo en una carpeta.

**Comment by giansalex** [comment]
Actualmente esos archivos no se guardan.
