### ISSUE TITLE
Modificacion del archivo invoice2.1.xml.twig

### ISSUE THREAD

**Issue by ChristDev** [giansalex/lycet#436]
Buenos dias, si deseo modificar el archivo invoice2.1.xml.twig, tengo q ejecutar algun comando para que me tome los cambios que ingrese o unicamente con restart el servicio deberia de refrescarse.?

**Comment by giansalex** [comment]
Deberias eliminar la carpeta `var/`

**Comment by ChristDev** [comment]
Gracias!!!
