### ISSUE TITLE
Attempted to load class soapclient

### ISSUE THREAD

**Issue by eilsongithub** [giansalex/lycet#45]
Estimados Sres... buenas tardes ... 
Estoy intentando implementar la ultima actualización de Lycet. pero obtengo este error en localhost
![image](https://user-images.githubusercontent.com/44086967/54773160-ff4f9180-4bd6-11e9-8f68-c50ade3bf815.png)
uso symfony 4
php 7.2

en web me da esto
![image](https://user-images.githubusercontent.com/44086967/54788286-7c413200-4bfc-11e9-983f-a25efcb32b6e.png)
php 7.2

me pueden ayudar?.

Saludos

**Comment by giansalex** [comment]
podrias borrar la carpeta vendor, y volver a instalar los paquetes.

**Comment by eilsongithub** [comment]
He descargado de nuevo, y he corrido nuevamente composer  install (composer v 1.8). pero persiste
![image](https://user-images.githubusercontent.com/44086967/54787545-020fae00-4bfa-11e9-8823-b59a73c9e17c.png)

talvez sea porque no obtengo esto en phpinfo
![image](https://user-images.githubusercontent.com/44086967/54787747-bc9fb080-4bfa-11e9-8a76-b77023bd3418.png)

he intentado varias veces...
descomentando php_soap.dll

 pero no logro ver  soap en php info

**Comment by giansalex** [comment]
Si, la extensión es requerida, si usas xampp actualiza desde la opción config que aparece en el UI,

**Comment by eilsongithub** [comment]
no estoy usando xampp ... 
ya no se como activarlo ... 
ya estoy varias horas intentando activarla ...

**Comment by eilsongithub** [comment]
instalé xampp, alli ya tengo soap ... sin embargo obtengo esto ... 
![image](https://user-images.githubusercontent.com/44086967/54790825-8e739e00-4c05-11e9-98fe-b062791340a9.png)

tratando de ingresar con swaggerui tengo esto. será por ello el error de no coneccion?
![image](https://user-images.githubusercontent.com/44086967/54790788-6b48ee80-4c05-11e9-9a70-97369bad6316.png)

**Comment by giansalex** [comment]
El primero es por problemas con el servicio de sunat (solo hay que volver a intentar).
Lo segundo, primero trata de abrir la URL que te muestra en otra pestaña, si carga entonces debe ser por CORS, en el archivo `.env` colocar en `CORS_ALLOW_ORIGIN=.`

**Comment by eilsongithub** [comment]
Estimado pero el servicio parece que está bien ... estoy probando con el anterior y si responde como aceptada apuntando al mismo servicio.

**Comment by eilsongithub** [comment]
con php7.3 
en web también hay un inconveniente
![image](https://user-images.githubusercontent.com/44086967/54852135-ed92ea80-4cb9-11e9-8307-7c8e3ebd52cc.png)

y el localhost 
![image](https://user-images.githubusercontent.com/44086967/54852175-10bd9a00-4cba-11e9-9594-17e04ca31f6a.png)

**Comment by Ajahuanex** [comment]
A mi me funciono con http://localhost/lycet/public/api/v1/invoice/send?token=123456 "invoice" no probe con "voided", esta última es otro servicio?. soy nuevo en esto. http://prntscr.com/n5f99f

**Comment by giansalex** [comment]
Hola @Ajahuanex, la ruta que aparece en la imagen `/voided` es para envio de comunicaciones de baja (Anular comprobantes).
