### ISSUE TITLE
Ayuda con el DockerFile

### ISSUE THREAD

**Issue by rayo80** [giansalex/lycet#472]
Cuando intento construir la imagen docker me sale esto :c

![image](https://user-images.githubusercontent.com/66443858/144724215-d2965ef4-a32f-4789-b8b7-6b22a3cb6b5a.png)

**Comment by giansalex** [comment]
Al parecer `wkhtmltopdf` no esta diponible en alpine `3.15`, intenta poner la version en la imagen base
```
FROM php:8.0-alpine3.14
```

**Comment by rayo80** [comment]
Si era eso ... gracias Dios de la facturación c:
