### ISSUE TITLE
PDF Report

### ISSUE THREAD

**Issue by OBSK** [giansalex/lycet#5]
Hola #giansalex al enviar una solicitud `axios.post('http://localhost:8000/api/v1/invoice/pdf', args, {
        params: {
        token: '123456'
        }
        }).then(res => console.log(res)).catch(err => console.log(err));`
En la consola obtengo **Uncaught Exception: The response content must be a string or object implementing __toString(), "boolean" given.**
¿Que puede estar pasando?
Muchas gracias por la respuesta.

**Comment by giansalex** [comment]
Probablemente esta ocurriendo un error al generar al pdf.
Puedes comprobar que `exec` no [esta deshabilitado](https://www.namecheap.com/support/knowledgebase/article.aspx/9396/2219/how-to-enable-exec), que la ruta de **wkhtmltopdf** exista.

**Comment by OBSK** [comment]
Puedo corroborar que la ruta **wkhtmltopdf** existe en el archivo .env del proyecto en **WKHTMLTOPDF_PATH=wkhtmltopdf** pero solo encuentro el archivo php.ini en la carpeta docker/config/. ¿Como compruebo que _exc_  no este habilitado? , estoy trabajando localmente.

**Comment by OBSK** [comment]
¿En donde habilito esa función?

**Comment by giansalex** [comment]
La extension `gd` en **php.ini**

**Comment by OBSK** [comment]
Me muestra el siguiente error **PHP Warning: Module 'gd' already loaded in Unknown on line 0** y después el mismo error.

**Comment by giansalex** [comment]
podrias revisar el proyecto https://github.com/giansalex/greenter-sample y verificar que se genere el PDF

**Comment by giansalex** [comment]
Hola @OBSK , agregue un cambio para que retorne el mensaje de error al generar PDF

**Comment by OBSK** [comment]
@giansalex muchas gracias. Descargando

**Comment by OBSK** [comment]
Hola @giansalex acabo de obtener el siguiente mensaje:
**"message": "Failed without error message: wkhtmltopdf --no-outline \"C:\\Users\\USUARIO\\AppData\\Local\\Temp\\tmp61C3.tmp.html\" \"C:\\Users\\USUARIO\\AppData\\Local\\Temp\\tmp61D3.tmp.pdf\""** también instale todos los paquetes para utilizar **wkhtmltopdf**

**Comment by giansalex** [comment]
- Has colocado la ruta absoluta de **wkhtmltopdf** en `.env`?
- Puedes probar wkhtmltopdf desde la linea de comando, algo como: `wkhtmltopdf.exe http://google.com google.pdf`

**Comment by OBSK** [comment]
La ruta en `.env` esta como `WKHTMLTOPDF_PATH=wkhtmltopdf`, pero al ejecutar `wkhtmltopdf.exe http://google.com google.pdf` en la consola obtengo este error: 
**Error: Unable to write to destination
Exit with code 1, due to unknown error.
**

**Comment by OBSK** [comment]
Lo mismo sucedió con el PATH, acabo de resolverlo. Espero que este issue pueda ayudar a alguien más en algún momento. Muchas gracias @giansalex.

**Comment by giansalex** [comment]
@eilsongithub debes instalar wkhtmltopdf, puedes usar [chocolatey ](https://chocolatey.org/packages/wkhtmltopdf)en windows
```
choco install wkhtmltopdf
```

**Comment by eilsongithub** [comment]
Gracias ...

**Comment by heiner25** [comment]
@giansalex una consulta, entiendo que para poder generar el pdf se necesita instalar wkhtmltopdf en la computadora, es así? y cuando la api esté en producción por ejemplo en un hosting compartido, entonces tendria que instalarlo alli también para que funcione? pero como haria esto? podrías orientarme por favor

**Comment by giansalex** [comment]
Solo necesitas subir el ejecutable al hosting, en caso sea linux, puedes descargar de [aqui](https://github.com/h4cc/wkhtmltopdf-amd64/tree/master/bin), e indicas la ruta completa en el archivo `.env` en la configuracion `WKHTMLTOPDF_PATH`

**Comment by eilsongithub** [comment]
Estimado giansalex .. subí el ejecutable a un directorio en mi hosting, sin embargo al descargar el pdf me sale esto:
{
    "message": "sh: /.../wkhtmltopdf.exe: Permission denied"
}
me podrías ayudar?

**Comment by giansalex** [comment]
|Tu hosting es windows?, dirigite a donde se encuentre wkhtmltopdf.exe, y dale los permisos para poder ejecutarse.

si es linux puedes descargarlo desde [aqui](https://github.com/h4cc/wkhtmltopdf-amd64/tree/master/bin)

**Comment by eilsongithub** [comment]
Efectivamente estimado giansalex, funcionó con el de linux

**Comment by DeveloperRafael1996** [comment]
Y CON INSTALLAR choco install wkhtmltopdf, SE SOLUCIONARA EL PROBLEMA, HABRA OTRA CONFIGURACION MAS POR HACER

**Comment by eilsongithub** [comment]
He hallado un inconveniente. Ojalá me puedan ayudar.
Lycet y el sistema que consulta la api. están en diferente hosting.
El tiempo de respuesta de la api al crear el PDF, demora como 35 segundos, un poco incomodo para el cliente ya que las ventas son rápidas y hay que imprimir el ticket desde el pdf, si creo otros inmediatamente el tiempo de respuesta es 4 segundo en promedio, pero si genera después de un tiempo mas largó vuelve a demorar 35 segundos aprox. (un poco incomodo ya que las ventas deben ser rápido).

**Comment by giansalex** [comment]
Verifica que hayas configurado symfony para PROD.
- En el archivo `.env`, debes cambiar el valor APP_ENV a prod
```
APP_ENV=prod
```
- Instalar paquetes optimizados.
```bash
composer install --no-interaction --no-dev --optimize-autoloader
php bin/console cache:clear --env=prod --no-debug
composer dump-autoload --optimize --no-dev --classmap-authoritative
```
- Otras optimizaciones son activa `opcache`, activar la versión mas reciente de PHP

**Comment by eilsongithub** [comment]
> * Instalar paquetes optimizados.
> 
> ```shell
> composer install --no-interaction --no-dev --optimize-autoloader
> php bin/console cache:clear --env=prod --no-debug
> composer dump-autoload --optimize --no-dev --classmap-authoritative
> ```


¿Esto se puede hacer sobre la carpeta que fue descargado de github de lycet?

....

**Comment by giansalex** [comment]
si claro

**Comment by Ajahuanex** [comment]
> Efectivamente estimado giansalex, funcionó con el de linux

- [ ] Hola @eilsongithub, podrias indicar que archivo descargaste? y si configuraste `php.ini`?

**Comment by eilsongithub** [comment]
> > Efectivamente estimado giansalex, funcionó con el de linux
> 
> * [ ]  Hola @eilsongithub, podrias indicar que archivo descargaste? y si configuraste `php.ini`?

Bueno mi caso era que en mi hosting no se podía generar el PDF, utilicé este archivo https://github.com/h4cc/wkhtmltopdf-amd64/tree/master/bin
y me parece que en el ini ya había estado configurado.

**Comment by Ajahuanex** [comment]
En mi caso, probé lo mismo, pero mi proveedor de hosting no quiere habilitar las funciones de ejecutables. Por ahora estoy probando alternativas como MPDF y DOMPDF, para reeplazar a MKHTMLTOPDF.
