### ISSUE TITLE
Configuración de múltiples empresas

### ISSUE THREAD

**Issue by volcanoxp** [giansalex/lycet#505]
¿Es posible configurar un end_point por cada negocio que se crea en el data/empresas.json?

**Comment by giansalex** [comment]
Si necesitas un endpoint diferente, puedes desplegar la aplicación en un diferente dominio o subdominoi.

**Comment by volcanoxp** [comment]
Una consulta, si yo configuró el data/empresas.json al hacer la petición de generar una factura cómo diferencia la API de a qué empresa pertenece la petición?

**Comment by giansalex** [comment]
Obtiene el ruc desde los datos de la empresa emisora, solo para el caso de consulta de estado de un resumen diario, se necesita enviar como parámetro el ruc `?ticket=2222&ruc=2000000000001`.
Creo que es algo que falta documentar.

**Comment by volcanoxp** [comment]
¿El parámetro ticket dónde se configura o obtiene?

**Comment by giansalex** [comment]
Cuando envías un resumen recibes como respuesta el `ticket` que luego utilizaras para consultar el estado.
