### ISSUE TITLE
Lycet con SQL server

### ISSUE THREAD

**Issue by yersey20037** [giansalex/lycet#512]
Buenas Tardes, tengo un sistema de facturacion que guarda los datos en una base de datos SQL server Express, es posible utilizar Lycet para hacer los envios a sunat o es mejor usar greenter?

necesito que se envie a sunat los documentos y me devuelva la respuesta para almacenarla en la base datos y almacenar el XML y el PDF en una carpeta de la computadora.
puedo tener algun inconveniente?

Gracias

**Comment by erajuan** [comment]
@yersey20037 no tendrias ningun incoveniente.
sería como un microservicio para facturación, puedes subir lycet tu heroku.
Recuerda que lycet no persiste archivos (xml/pdf)

**Comment by yersey20037** [comment]
@erajuan, gracias, y sabes como podria hacer para que al generar el xml y pdf lo guarde en mi pc teniendo en cuenta que lo voy a ejecutar en la misma ps en un local host.

**Comment by yersey20037** [comment]
en la mism pc tengo el sistema de facturación, el SQL server y el localhost con Lycet y aqui mismo quiero que se guarde el XML y el PDF en una carpeta especifica que yo designe.
Gracias
