### ISSUE TITLE
factura con item exonerado error

### ISSUE THREAD

**Issue by yersey20037** [giansalex/lycet#513]
Buenas noches estoy intentando enviar una factura con 3 item uno de ellos es exonerado de impuesto y me devuelve el error:
El importe total de impuestos por línea no coincide con la sumatoria de los impuestos por línea
error: Error en la linea: 3: 3292 (nodo: \"cac:TaxTotal/cbc:TaxAmount\" valor: \"0.00\")
esto estoy enviando:
{
"ublVersion": "2.1",
"tipoOperacion": "0101",
"tipoDoc": "01",
"serie": "F112",
"correlativo": "00000360",
"fechaEmision": "2022-05-17T11:19:04+51:00",
    "formaPago": {
        "tipo": "Contado"
    },
"client": {
"tipoDoc": "6",
"numDoc": "20548194475",
"rznSocial": "GOLDEN CONSULTING S.A.C.",
"address": {
"ubigueo": "140124",
"codigoPais": "PE",
"departamento": "Lima",
"provincia": "Lima",
"distrito": "San Isidro",
"urbanizacion": "Santa cruz",
"direccion": "Av. las Camelias Nro. 877 Int. 302",
"codLocal": "0000"
}
},
"company": {
"ruc": "22222222222",
"razonSocial": "CORPORACION PEPITO SAC",
"nombreComercial": "PEPITO MARKET",
"address": {
"ubigueo": "160102",
"codigoPais": "PE",
"departamento": "-",
"provincia": "-",
"distrito": "-",
"urbanizacion": "-",
"direccion": "-",
"codLocal": "0000"
}
},
"tipoMoneda": "PEN",
"mtoOperExoneradas": 8.90,
"mtoIGV": 1.64,
"subTotal": 18.06,
"totalImpuestos": 1.64,
"valorVenta": 18.06,
"mtoImpVenta": 19.70,
"details": [
{
"unidad": "NIU",
"cantidad": 1,
"codProducto": "7750863409016",
"descripcion": "LA CALERA HUEVOS PARDO X15",
"mtoValorUnitario":8.90,
"mtoBaseIgv":8.90,
"porcentajeIgv":0,
"igv":0,
"tipAfeIgv":"20",
"TotalImpuestos":0,
"mtoPrecioUnitario":8.90,
"mtoValorVenta":8.90
},
{
"unidad": "NIU",
"cantidad": 1,
"codProducto": "7750298000710",
"descripcion": "SAN LUIS C/G 2.50 ML",
"mtoValorUnitario": 3.31,
"mtoBaseIgv": 3.31,
"porcentajeIgv": 18,
"igv": 0.59,
"tipAfeIgv": "10",
"TotalImpuestos": 0.59,
"mtoPrecioUnitario": 3.90,
"mtoValorVenta": 3.31
},
{
"unidad": "NIU",
"cantidad": 1,
"codProducto": "7750427000888",
"descripcion": "VALLE ALTO MIX UP 150 GR",
"mtoValorUnitario": 5.85,
"mtoBaseIgv": 5.85,
"porcentajeIgv": 18,
"igv": 1.05,
"tipAfeIgv": "10",
"TotalImpuestos": 1.05,
"mtoPrecioUnitario": 6.90,
"mtoValorVenta": 5.85
}
],
"legends": [
{
"code": "1000",
"value": "Diecinueve CON 70 /100 SOLES"
}
]
}

alguna observación de porque me da este error?

**Comment by yersey20037** [comment]
el error se genera porque le envio solo 2 decimales y es necesario enviar mas para que el calculo sea exacto

**Comment by giansalex** [comment]
@yersey20037 siempre manejar todos los decimales, internamente greenter maneja el formateo a 2 decimales segun sea el caso.
