### ISSUE TITLE
consumo de lycet instalado en localhost con xampp desde angular tambien en localhost (error de CORS)

### ISSUE THREAD

**Issue by yersey20037** [giansalex/lycet#517]
buenas tardes, tengo instalado Lycet en xampp el local host y lo quiero consumir desde angular tambien en local host pero me da error de CORS .
Ya se que esto de los CORS solo se da cuando la conexion es atravez de la web pero deseo utilizar angular para esto por motivos de utilizarlo para otros temas mas del sistema al mismo tiempo.
ya revise las configuraciones y no encuentro porque me bloquea por mas configuraciones que probe no me permite la conexion.
voy a trabajar todo en local para los envios a sunat. asi que descarto usarlo en un hosting.
desde postman no tengo ningun problema para el envio del mismo JSON
podrian darme una ayuda de que es lo que tengo que cambiar para que acepte la conexion desde angular en localhost?
![imagen](https://user-images.githubusercontent.com/56704596/170907685-c2de9063-6916-45ea-8ba2-a605c61ebd5b.png)
![imagen](https://user-images.githubusercontent.com/56704596/170907768-756dfec6-5908-4478-a535-66cc09c6876a.png)

**Comment by giansalex** [comment]
Cors esta habilitado por defecto
https://github.com/giansalex/lycet/blob/4e9308be35822918f7cfc92fc6d7afeb8df78713/.env#L23

**Comment by yersey20037** [comment]
Hola @giansalex , actualize la pregunta adjuntando captura de como hago el llamado al api

**Comment by giansalex** [comment]
Tambien podrias intentar añadir `allow_origin: ['*']` aqui
https://github.com/giansalex/lycet/blob/master/config/packages/nelmio_cors.yaml#L10
```yaml
        '^/api':
          allow_origin: ['*']
          allow_methods: ['POST', 'GET']
          max_age: 3600
```

**Comment by yersey20037** [comment]
@giansalex cambiado pero con el mismo problema:
![imagen](https://user-images.githubusercontent.com/56704596/170909403-6d84ec88-ea75-444e-8db5-0a2c727c37ea.png)
![imagen](https://user-images.githubusercontent.com/56704596/170909450-ae173511-08df-415b-9a48-74ff9d1b1826.png)
![imagen](https://user-images.githubusercontent.com/56704596/170909463-e98b5e45-556e-4d2b-9c6f-1431b202c30f.png)

**Comment by yersey20037** [comment]
@giansalex al hacer clic en la ruta que me marca error en la consola veo este mensaje de Symfony
![imagen](https://user-images.githubusercontent.com/56704596/170912533-5906943b-c0f6-4793-a50a-9847305ef6b3.png)

**Comment by giansalex** [comment]
puedes intentar invocar localhost:8000/ desde angular y si funciona, entonces el problema es la validación de ese token.

se tendria que agregar este codigo en esta [linea ](https://github.com/giansalex/lycet/blob/4e9308be35822918f7cfc92fc6d7afeb8df78713/src/EventSubscriber/TokenSubscriber.php#L37)
```php
        if ($event->getRequest()->getMethod() === 'OPTION') {
            return;
        }
```
