### ISSUE TITLE
Puede usarse lycet para conectarse a una OSE?

### ISSUE THREAD

**Issue by rayo80** [giansalex/lycet#524]
Probe boleta, factura y nota de crédito  cambiando la url del dockerfile(multiempresas) y mande a NUBEFACT sin problemas en beta. Nubefact me valida cuando se hacen envia el documento dos veces,tbn detecta documentos fuera de fecha en beta.

**Comment by erajuan** [comment]
@rayo80 
puedes generar el XML y enviar al OSE de tu preferencia. (por ahora lycet no envia directo a una OSE)
