### ISSUE TITLE
Problema con el docker

### ISSUE THREAD

**Issue by rayo80** [giansalex/lycet#525]
Trabajaba con normalidad pero justo hace un rato me salio este error al intentar construir la imagen...hoy no es mi dia
![image](https://user-images.githubusercontent.com/66443858/176804627-d43a6352-e95d-47cc-8220-5a4861662f86.png)
![image](https://user-images.githubusercontent.com/66443858/176804732-c36b7fd3-c1c2-48ba-b871-dcadbc28b1b9.png)

**Comment by giansalex** [comment]
Vuelve a clonarlo, subí una corrección.

**Comment by rayo80** [comment]
si ya se arreglo
