### ISSUE TITLE
Me sale un error al instalar Lycet con Docker

### ISSUE THREAD

**Issue by hbars3** [giansalex/lycet#543]
Saludos a la comunidad.
Tengo instalado Docker version 20.10.17, build 100c701
Y al seguir los pasos de instalación de lycet con Docker tengo este error

![image](https://user-images.githubusercontent.com/86030471/190724558-5d8b51f9-e322-4ca9-8b3f-0575a6314dd6.png)

Pueden ayudarme porfavor?

**Comment by keynerajs93** [comment]
@hbars3 en el docker file añade el siguiente código después de ENV APP_ENV test:

`
ENV COMPOSER_ALLOW_SUPERUSER 1`
