### ISSUE TITLE
STATUS BAJA ERROR

### ISSUE THREAD

**Issue by mario125** [giansalex/lycet#553]
Me sale el siguiente error :
{
    "success": false,
    "error": {
        "code": "env:Server",
        "message": "Internal Error (from server)"
    }
}

mis rutas en produccion:
#PRODUCTION
FE_URL=https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService
RE_URL=https://e-factura.sunat.gob.pe/ol-ti-itemision-otroscpe-gem/billService
GUIA_URL=https://e-guiaremision.sunat.gob.pe/ol-ti-itemision-guia-gem/billService

**Comment by giansalex** [comment]
Es un error en los servidores de sunat
