### ISSUE TITLE
Consulta si ya esta integrada las nuevas validaciones de Guias electronicas que puso sunat?

### ISSUE THREAD

**Issue by yersey20037** [giansalex/lycet#556]

**Comment by Sephit** [comment]
Aun no

**Comment by augustosamame** [comment]
Y ahora ya están? En caso no lo estén, como podría ayudar?

**Comment by giansalex** [comment]
Si, ya esta incluido. Aqui hay unos ejemplos https://www.postman.com/greenter/workspace/lycet/folder/1442354-75dd1867-4f50-4854-9771-a0640a834d13?ctx=documentation
