### ISSUE TITLE
Comunicación de bajas - boletas de venta

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#56]
Buen día, acabo de habilitar la comunicación de bajas; y al realizar las pruebas me dí cuenta que no puedo comunicar boletas de venta...
No sé si estoy mal, pero documentándome en [http://orientacion.sunat.gob.pe/index.php/empresas-menu/comprobantes-de-pago-empresas/comprobantes-de-pago-electronicos-empresas/see-desde-los-sistemas-del-contribuyente/2-comprobantes-que-se-pueden-emitir-desde-see-sistemas-del-contribuyente/factura-electronica-desde-see-del-contribuyente/3529-operatividad]

Explica que se puede hacer las notificaciones de baja tanto para boletas como para facturas.

Espero puedan darme alguna respuesta, gracias de antemano

**Comment by giansalex** [comment]
Actualmente las boletas se dan de baja usando el mismo resúmen diario, en campo Estado=3. Mucha de esa documentación está desactualizada y olvidada.

**Comment by OD-n** [comment]
oh, vaya, perfecto... gracias;

**Comment by RiWAR** [comment]
> Actualmente las boletas se dan de baja usando el mismo resúmen diario, en campo Estado=3. Mucha de esa documentación está desactualizada y olvidada.

Pero si el resumen diario incluye varias boletas, como señalas cual es la boleta a anular.

**Comment by giansalex** [comment]
@RiWAR , cada item de Boleta en el xml tiene el campo `Estado`.
