### ISSUE TITLE
Error! 0306 - No se puede leer (parsear) el archivo XML 

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#567]
Al intentar enviar un comprobante acabo de obtener un mensaje de error, en especifico el siguiento:
Error! 0306 - No se puede leer (parsear) el archivo XML - Detalle: local:///commons/xsl/validation/2.X/ValidaExprRegFactura-2.0.1.xsl:629: local:///commons/xsl/validation/2.X/ValidaExprRegFactura-2.0.1.xsl:629: Call to unknown template isTrueExpresionEmptyNode, no escuentro alguna respuesta, espero me puedan ayudar si a alguien mas le esta pasando este error.

**Comment by giansalex** [comment]
Al parecer nuevas validaciones que agrego SUNAT, pero no ha funcionado bien, es un problema que ellos tienen que arreglar.

**Comment by augustosamame** [comment]
Se solucionó este problema?

**Comment by giansalex** [comment]
@augustosamame probablemente, ya no veo que estén reportando este problema.
