### ISSUE TITLE
Error al crear la imagen de docker

### ISSUE THREAD

**Issue by rcjuancarlosuwu** [giansalex/lycet#598]
Error:
<img width="737" alt="image" src="https://github.com/giansalex/lycet/assets/67658540/8054ef20-7e40-4770-9ba0-f933f4a1639a">

Pasos para reproducir:

```
git clone https://github.com/giansalex/lycet
cd lycet
docker build -t lycet .
docker run -d -p 8000:8000 --name lycet_app lycet 
```

Al parecer es debido a que no encuentra el paquete `wkhtmltopdf`

**Comment by giansalex** [comment]
El paquete wkhtmltopdf solo existe hasta la version `alpine3.14`, acabo de subir una actualizacion del Dockerfile https://github.com/giansalex/lycet/commit/2375bca2a5f148e54ced711a363e3984861004b0
