### ISSUE TITLE
No se muestra imagen en PDF

### ISSUE THREAD

**Issue by OBSK** [giansalex/lycet#6]
Hola @giansalex, al cargar la imagen en base64 y el certificado .PEM con el editor de **swagger** o con la herramienta [https://giansalex.github.io/lycet-ui-config/](url) no cargan los datos adecuadamente, tuve que agregarlos manualmente desde el directorio. Aún así la imagen del logo sigue sin cargarse en el PDF para generar una factura o boleta electrónica.

**Comment by giansalex** [comment]
No muestra algún mensaje de alerta?

**Comment by OBSK** [comment]
No, en el log no muestra ningún error.

**Comment by giansalex** [comment]
Acerca de lycet-ui-config, lo revise y si envía la información correctamente; acerca de la imagen en el PDF, lo revisaré.

**Comment by giansalex** [comment]
si hubo un problema al mostrar la imagen en pdf, ahora esta corregido
