### ISSUE TITLE
@OD-n en `empresas.json` tambien debe incluir los campos `CLIENT_ID` y `CLIENT_SECRET`

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#605]
Perfecto, acabo de colocar los campos en el empresas.json y ya puedo realizar las pruebas. Gracias.
{
    "20161515648": {
        "SOL_USER": "20161515648MODDATOS",
        "SOL_PASS": "MODDATOS",
        "certificate": "20161515648/cert.pem",
        "logo": "20161515648/logo.png",
        "nombre": "TEST2",
        "CLIENT_ID": "test-85e5b0ae-255c-4891-a595-0b98c65c9854",
        "CLIENT_SECRET": "test-Hty/M6QshYvPgItX2P0+Kw=="
    }
}

**Comment by giansalex** [comment]
Perfecto, lo agregue como referencia al README https://github.com/giansalex/lycet/commit/d806aee7f722cffbe685efb5545560e22566eee3

Referencia #595

**Comment by OD-n** [comment]
Acabo de generar las credenciales en el portal de SUNAT, desde la sección para registrar una API SUNAT.
![image](https://github.com/giansalex/lycet/assets/28074529/e85920f0-b4b8-48bc-9389-a6d1384c0cf9)

Copiando el "id" y "clave" en el empresa.json.
![image](https://github.com/giansalex/lycet/assets/28074529/32376075-c7ad-463a-b77a-d9b77be98dc5)

Pero aún así tengo el error de cliente no autorizado, trate de realizar el envio por POSTMAN y me apareció la respuesta de Cliente no Autorizado
![image](https://github.com/giansalex/lycet/assets/28074529/8fafffd7-04df-4071-b532-c5725236e345)

Quisiera saber si hay algo mas que tengo que configurar o no está bien en donde he creado el client_id y client_secret, o es algo mas
