### ISSUE TITLE
NOTA DE CREDITO CON MONTO 0

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#621]
Queria ver como se deberia crear una nota de crédito con monto 0, para modificar detalle o por error en descripción o algo similar, en esos casos no se agregan nada en details (que son los items).

**Comment by giansalex** [comment]
Puedes hacer esas consultas en el chat de TG https://t.me/thegreenter

**Comment by OD-n** [comment]
Gracias por la respuesta, lo haré por ese medio, muchas gracias.
