### ISSUE TITLE
Configuración multiempresa

### ISSUE THREAD

**Issue by EliuTimana** [giansalex/lycet#64]
Existe la posibilidad de almacenar múltiples certificados, logos y credenciales sunat? para poder tener multiples emisores y no solo uno.
por ahora esos datos se extraen desde variables de entorno, ¿que tanto habria que modificar para conseguirlo?

**Comment by giansalex** [comment]
Hola @EliuTimana , algo simple podria ser llevar las credenciales a un archivo (json, yaml), y en la carpeta data almacenar el certificado y el logo teniendo como nombre el ruc del emisor.

**Comment by giansalex** [comment]
@EliuTimana si fuera posible que contribuyeras con eso, también podría ayudarte. 😃

**Comment by EliuTimana** [comment]
Claro, he estado revisando el código y ya he identificado mas o menos los cambios, tengo pensado implementarlo. :+1:

**Comment by CarlosTTRR** [comment]
Muy pronto trataré de hacer un cambio similar en este proyecto. Para manejo multiempresas.
Slds.

**Comment by giansalex** [comment]
Hola @CarlosTTRR, seria de gran aporte.

**Comment by OD-n** [comment]
@giansalex  que tan difícil sería para la configuración multiempresa alojar el logo y certificado dentro de data ( en una carpeta con su RUC)
Antes: 
|--data/
|    |--logo.png
|    |--cert.pem

Lo que quisiera hacer:
|--data/
|    |--100000000001/
|              |--logo.png
|              |--cert.pem
|    |--200000000002/
|              |--logo.png
|              |--cert.pem
|    |--200000000003/
|              |--logo.png
|              |--cert.pem

y los cambios que se tendría que hacer estaría en:
`   public function get($key)
    {
        if (!isset($this->keys[$key])) {
            return '';
        }

        if($empresa==null){
            return '';
        }else{
            $path = $this->directory.DIRECTORY_SEPARATOR.(aqui iría el RUC de la empresa).DIRECTORY_SEPARATOR.$this->keys[$key];
        }

        if (file_exists($path)) {
            return file_get_contents($path);
        }

        return '';
    }`

Espero puedas ayudarme con ello, y si es factible hacerlo de esa manera o que otros cambios tendría que hacer

**Comment by JhonnySA** [comment]
> Hola @EliuTimana , algo simple podria ser llevar las credenciales a un archivo (json, yaml), y en la carpeta data almacenar el certificado y el logo teniendo como nombre el ruc del emisor.

Estimado @giansalex antes de nada agradecer por esta herramienta muy importante. Estoy implementado la sugerencia que propusiste lineas arriba, sin embargo no tengo una idea clara de que archivos modificar o si tengo que agregar algun archivo de configuracion.

Agradezco tu respuesta ya que sera de gran ayuda

**Comment by giansalex** [comment]
Hola @OD-n , @JhonnySA se puede crear un archivo config.json
```json
{
  "empresas": [
    {
      "ruc": "20000000001",
      "usuario": "MODDATOS",
      "clave": "moddatos",
      "certificado": "cert1.pem",
      "logo": "logo1.png"
    },
    {
      "ruc": "20000000002",
      "usuario": "TEST",
      "clave": "test",
      "certificado": "cert2.pem",
      "logo": "logo2.png"
    }
  ]
}
```
los certificados y logos serian los nombres dentro de la carpeta data, la obtencion de la informacion puede realizarse en el metodo [getSee()](https://github.com/giansalex/lycet/blob/master/src/Service/DocumentRequest.php#L168)

**Comment by JhonnySA** [comment]
> Hola @OD-n , @JhonnySA se puede crear un archivo config.json
> 
> ```json
> {
>   "empresas": [
>     {
>       "ruc": "20000000001",
>       "usuario": "20000000001MODDATOS",
>       "clave": "moddatos",
>       "certificado": "cert1.pem",
>       "logo": "logo1.png"
>     },
>     {
>       "ruc": "20000000002",
>       "usuario": "20000000002TEST",
>       "clave": "test",
>       "certificado": "cert2.pem",
>       "logo": "logo2.png"
>     }
>   ]
> }
> ```
> 
> los certificados y logos serian los nombres dentro de la carpeta data, la obtencion de la informacion puede realizarse en el metodo [getSee()](https://github.com/giansalex/lycet/blob/master/src/Service/DocumentRequest.php#L168)

Gracias @giansalex por tu respuesta, estoy tratando de encontrar el lugar donde recoger el parametro, en este caso seria el RUC, el cual se tendria que enviar por URL para buscar en mi json de Empresas, me podrias brindar alguna sugerencia de donde poder hacerlo, estoy empezando con Symfony. Espero puedas ayudarme

**Comment by giansalex** [comment]
Para el caso de los comprobantes el ruc ya esta en el campo `$company->getRuc()`, solo seria necesario el ruc en el endpoint [/status](url)

**Comment by JhonnySA** [comment]
> Para el caso de los comprobantes el ruc ya esta en el campo `$company->getRuc()`, solo seria necesario el ruc en el endpoint `/status`

Gracias @giansalex  por tu respuesta, tratare de entender y hacer lo que recomiendas

**Comment by JhonnySA** [comment]
> Para el caso de los comprobantes el ruc ya esta en el campo `$company->getRuc()`, solo seria necesario el ruc en el endpoint `/status`

> > Hola @OD-n , @JhonnySA se puede crear un archivo config.json
> > ```json
> > {
> >   "empresas": [
> >     {
> >       "ruc": "20000000001",
> >       "usuario": "20000000001MODDATOS",
> >       "clave": "moddatos",
> >       "certificado": "cert1.pem",
> >       "logo": "logo1.png"
> >     },
> >     {
> >       "ruc": "20000000002",
> >       "usuario": "20000000002TEST",
> >       "clave": "test",
> >       "certificado": "cert2.pem",
> >       "logo": "logo2.png"
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> > los certificados y logos serian los nombres dentro de la carpeta data, la obtencion de la informacion puede realizarse en el metodo [getSee()](https://github.com/giansalex/lycet/blob/master/src/Service/DocumentRequest.php#L168)
> 
> Gracias @giansalex por tu respuesta, estoy tratando de encontrar el lugar donde recoger el parametro, en este caso seria el RUC, el cual se tendria que enviar por URL para buscar en mi json de Empresas, me podrias brindar alguna sugerencia de donde poder hacerlo, estoy empezando con Symfony. Espero puedas ayudarme

Estimado @giansalex esto es lo que estoy modificado en el metodo `getSee()`, talvez no sea la mejor forma de obtener el RUC de la empresa que esta haciendo la peticion, sin embargo como sugeriste `$company->getRuc()` no encuentro forma de llamarlo para obtenerlo de una forma mas limpia.
![image](https://user-images.githubusercontent.com/36165052/62745595-5aacdf80-ba11-11e9-933f-b1a2ca5a2ebd.png)
Para obtener el logo lo tengo de forma similar
![image](https://user-images.githubusercontent.com/36165052/62745956-f428c100-ba12-11e9-9d56-8282787863ac.png)
Asi seria la estructura de mis archivos en data
![image](https://user-images.githubusercontent.com/36165052/62745822-4ae1cb00-ba12-11e9-96b5-9692a073720b.png)

Espero puedas darme tu punto de vista sobre cuan eficiente seria, Gracias de antemano

**Comment by giansalex** [comment]
podrias pasar RUC como parámetro a `getSee($ruc)`, luego en esta [linea](https://github.com/giansalex/lycet/blob/master/src/Service/DocumentRequest.php#L86) puedes enviar el ruc como `$see = $this->getSee($document->getCompany()->getRuc());`,
Acerca del logo solo necesitas el `file_get_contents()`

**Comment by JhonnySA** [comment]
> podrias pasar RUC como parámetro a `getSee($ruc)`, luego en esta [linea](https://github.com/giansalex/lycet/blob/master/src/Service/DocumentRequest.php#L86) puedes enviar el ruc como `$see = $this->getSee($document->getCompany()->getRuc());`,
> Acerca del logo solo necesitas el `file_get_contents()`

Excelente @giansalex , funciona, voy a intentar implementarlo ahora con una tabla

**Comment by JhonnySA** [comment]
@giansalex tengo una consulta, sobre una instalacion limpia de Lycet, configure mi archivo `.env` a urls de produccion y la respuesta que obtengo son las de prueba, lo se porque estoy intentando enviar 2 veces el mismo comprobante que ya ha sido informado anteriormente a Sunat, y la respuesta es que ha sido sido aceptado correctamente; ¿Los cambios que tengo que realizar solo serian en el archivo `.env` o existe algun otro archivo que se este usando?

**Comment by giansalex** [comment]
Para estar seguro de eso, puedes revisar el xml del CDR, alli debería estar la firma de Sunat o indicar que es Beta.
En esta [linea](https://github.com/giansalex/lycet/blob/master/.env#L17) deberia setear `prod`, tambien eliminar cualquier otro archivo .env.xx

**Comment by JhonnySA** [comment]
Lo tengo configurado asi:
![image](https://user-images.githubusercontent.com/36165052/63180420-da3f3d80-c013-11e9-8c03-70333e919415.png)

**Comment by giansalex** [comment]
Verifica que en esta [linea](https://github.com/giansalex/lycet/blob/master/src/Service/DocumentRequest.php#L195) este retornando la url correcta, tambien puedes intentar borrar la carpeta `/var`

**Comment by JhonnySA** [comment]
Hay varios lugares donde he intentado imprimir valores para guiarme de donde puedo hacer cambios, sin embargo  en varios de ellos la respuesta es algo vacio
![image](https://user-images.githubusercontent.com/36165052/63182888-39538100-c019-11e9-9848-6cc361ec0481.png)

![image](https://user-images.githubusercontent.com/36165052/63182935-58521300-c019-11e9-8e0f-4f3f6a978b41.png)

**Comment by JhonnySA** [comment]
Probe de esta forma
![image](https://user-images.githubusercontent.com/36165052/63184719-9e10da80-c01d-11e9-8340-fb208b7fe14e.png)

y obtuve esto
![image](https://user-images.githubusercontent.com/36165052/63184810-d6181d80-c01d-11e9-8008-e8c14bdd4523.png)

**Comment by giansalex** [comment]
Intentaré hacer una prueba, aparentemente el problema es al obtener los valores de `.env`

**Comment by giansalex** [comment]
Hola @JhonnySA, acerca del problema que tenias al obtener las variables con `getenv`, el problema ocurrio desde que se actualizo a  symfony v4.3. 
Ha sido corregido en 4edb26afa2fd442ba572ec7934326e5ff5a23cb4

**Comment by JhonnySA** [comment]
Gracias @giansalex por tu tiempo y tu respuesta, logre hacerlo tomando una copia anterior de Lycet, con el cual no tuve inconvenientes, vi que lograron agregarlo con una configuracion de un archivo JSON, me preguntaba como podria hacer para incluir mis cambios al proyecto, lo termine con una conexion a una base de datos y agrege codigo para subir los archivos de cada empresa en el path de `configuration`

**Comment by giansalex** [comment]
Hola @JhonnySA, si quieres incluir tus cambios tendrías que hacer un fork al repositorio, luego pasar los cambios subirlos a ese repositorio, y de allí tendrías la opción de enviar un pull request
