### ISSUE TITLE
documentos electrónicos no son visibles en consulta validez

### ISSUE THREAD

**Issue by OBSK** [giansalex/lycet#71]
Hola @giansalex, hace unas semanas acabo de probar LYCET, el problema es que cuando envío los documentos a la SUNAT me muestra el mensaje que el comprobante fue aceptado con codigo "0", sin embargo al consultar la validez del CPE, sale que no existe en los registros de la SUNAT. ¿Que puede estar pasando?. Gracias por tu respuesta.

**Comment by giansalex** [comment]
Estas seguro de estar usando la ruta de servicio correcto, porque puede ser que se haya enviado a BETA

**Comment by OBSK** [comment]
Si, estoy usando el servicio correcto, ya que al ingresar al portal de la SUNAT y consultar los comprobantes electrónicos sale con estado procesado, pero al consultar la validez del comprobante me muestra que no ha sido informada.

**Comment by OBSK** [comment]
Esto son los parámetros de envío: 
{"ublVersion":"2.1","tipoOperacion":"0101","tipoDoc":"01","serie":"F001","correlativo":2004,"fechaEmision":"2019-04-23T10:20:41-05:00","client":{"tipoDoc":6,"numDoc":"20494052190","rznSocial":"HUIMA MOTOR'S S.A.C.","address":{"ubigueo":"220901","departamento":"San Martin","provincia":"San Martin","distrito":"San Martin","urbanizacion":"NONE","direccion":"JR. RICARDO PALMA NRO."}},"company":{"ruc":10008842499,"razonSocial":"ANTEZANA VELASQUEZ PAULINO EDGAR","nombreComercial":"ANTEZANA VELASQUEZ PAULINO EDGAR","address":{"ubigueo":"220901","departamento":"San Martín\n","provincia":"San Martín\n","distrito":"Tarapoto\n","urbanizacion":"NONE","direccion":"JR. PROGRESO NRO. S/N"}},"tipoMoneda":"PEN","sumOtrosCargos":0,"mtoOperGravadas":0,"mtoOperInafectas":0,"mtoOperExoneradas":6,"mtoIGV":0,"mtoISC":0,"mtoOtrosTributos":0,"mtoImpVenta":6,"valorVenta":6,"details":[{"unidad":"NIU","cantidad":1,"codProducto":"01","descripcion":"Bujia CR9EH-9 NGK/CG150/Brasil","mtoValorUnitario":6,"descuento":0,"mtoOperGratuitas":0,"mtoBaseIgv":6,"porcentajeIgv":0,"igv":0,"TotalImpuestos":0,"tipAfeIgv":"20","mtoValorGratuito":0,"mtoPrecioUnitario":6,"mtoValorVenta":6}],"legends":[{"code":"1000","value":"SON SEIS NUEVOS SOLES "},{"code":"2001","value":"Bienes transferidos en la amazonia para ser consumidos en la misma."}]}

**Comment by giansalex** [comment]
Si los has visto en el portal de sunat, entonces podrás darte cuenta que no aparezca en la consulta de validez, es un problema de ellos.  Deberías llamar a sunat.

**Comment by OBSK** [comment]
Gracias, es extraño que este pasando eso, si alguien tuviera un problema similar me gustaría que lo comente, muchas gracias.
