### ISSUE TITLE
Resumen diario - Nota de crédito

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#72]
Hola @giansalex, Estoy probando el envío del resumen diario y todo perfecto, pero al intentar enviar notas notas de credito de boletas electronicas tengo el siguiente error:

> "No existe información de serie o número. - Detalle: xxx.xxx.xxx value='ticket: 1555974791671 error: Error en la linea: 1. Solo se acepta informacion de comprobantes de referencia para notas (Credito o debito): el tipo de comprobante es: 07 y debe de ser 07 o 08.'"

El JSON que estoy enviando es el siguiente:
`{
    "correlativo": "11159",
    "fecGeneracion": "2019-02-18T12:00:00+02:00",
    "fecResumen": "2019-02-21T12:00:00+00:00",
    "moneda": "PEN",
    "company": {
      "ruc": "20123456789",
      "razonSocial": "REST. MORALY",
      "nombreComercial": "MORALY",
      "address": {
        "ubigueo": "180101",
        "codigoPais": "PE",
        "departamento": "MOQUEGUA",
        "provincia": "MARISCAL NIETO",
        "distrito": "MOQUEGUA",
        "urbanizacion": "-",
        "direccion": "CALLE LIMA 398"
      }
    },
    "details": [
      {
        "tipoDoc": "07",
        "serieNro": "BC01-00000008",
        "clienteTipo": "1",
        "clienteNro": "47719456",
        "estado": "3",
        "total": "25.00",
        "mtoOperGravadas": "21.19",
        "mtoIGV": "3.81"
      }
    ]
  }`

Espero puedas ayudarme, gracias de antemano

**Comment by giansalex** [comment]
es por que no se ha enviado la informacion del comprobante de refencia, que seria la boleta que afecta.

**Comment by OD-n** [comment]
ahhh... ok ok... acabo de probarlo, todo funciona perfectamente.
