### ISSUE TITLE
Fetch error Possible cross-origin (CORS) issue

### ISSUE THREAD

**Issue by Ajahuanex** [giansalex/lycet#81]
Alguna solución? ya que en versiones anteriores no salia este error.
`Fetch error
Possible cross-origin (CORS) issue? The URL origin (http://localhost) does not match the page (http://petstore.swagger.io). Check the server returns the correct 'Access-Control-Allow-*' headers.`

**Comment by Ajahuanex** [comment]
Sin embargo con postman todo va bien.
![Screenshot_1](https://user-images.githubusercontent.com/2767765/58443975-44061600-80bb-11e9-8eb5-9d4b48af6d8e.png)

**Comment by giansalex** [comment]
El tema de cors toma efecto en el navegador, de tal modo que si se usa desde cualquier otra aplicacion, no habra problema.
Si quieres usarlo desde el dominio de swagger, tendras que habilitarlo desde en [.env](https://github.com/giansalex/lycet/blob/57aa24b376b39cc24147b84d6d8cbecb41602cbc/.env#L24), puedes tambien colocar `CORS_ALLOW_ORIGIN=.` para permitir desde cualquier dominiol.

**Comment by Ajahuanex** [comment]
Gracias por la respuesta rápida, estoy probando en mi hosting, hice lo mismo pero me sale error de compilacion. 
![Screenshot_2](https://user-images.githubusercontent.com/2767765/58446208-6a30b380-80c5-11e9-83db-ca2e5e11cb85.png)

**Comment by Ajahuanex** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/2767765/58446260-bb40a780-80c5-11e9-9eaf-f3da28ad6d5f.png)

**Comment by Ajahuanex** [comment]
El problema de acceso CORS tenias razón,

- Solución: "CORS_ALLOW_ORIGIN=. " 
![Screenshot_4](https://user-images.githubusercontent.com/2767765/58447278-89c9db00-80c9-11e9-9459-ebd4224cea28.png)

Pero sigo teniendo problemas con el error de compilacion en un host remoto, porque en el local todo bien.

**Comment by giansalex** [comment]
En el hostal remoto puedes intentar borrando la carpeta `var/`

**Comment by Ajahuanex** [comment]
Borre la carpeta "/var" , pero persiste el problema tambien probé con swagger y el tipo de error sale "Failed to fetch".
![Screenshot_6](https://user-images.githubusercontent.com/2767765/58447966-e4fccd00-80cb-11e9-9a78-30b3982f4331.png)

**Comment by Ajahuanex** [comment]
De echo probando tu swagger oficial me da el mismo error.
![Screenshot_8](https://user-images.githubusercontent.com/2767765/58449413-10ce8180-80d1-11e9-921f-7ff1824eb5bd.png)

**Comment by giansalex** [comment]
El problema no está relacionado con swagger, es con la librería jms serializer, pero realmente no me he topado con ese error, intenta volver instalar los paquetes , dar permisos a la carpeta var/ , buscar ese error por internet.

**Comment by Ajahuanex** [comment]
Por fin funciono, pero con una version anterior de Lycet .
![Screenshot_9](https://user-images.githubusercontent.com/2767765/58452221-3f9e2500-80dc-11e9-9297-6634cac7ac00.png)

**Comment by giansalex** [comment]
Hola @Ajahuanex , podrías compartir el hash de ultimo commit de esa versión, para verificar que podría estar causando ese problema.

**Comment by Ajahuanex** [comment]
Soy nuevo en github, espero que sea  el hash que me pides `"content-hash": "315984f19db7ef1f87e0af855e72681e"` estaba en composer.lock

**Comment by giansalex** [comment]
Si es correcto. Que versión de PHP usas?

**Comment by Ajahuanex** [comment]
En el host remoto `ea-php71`,  y en el local la version de PHP es 7.2.11

**Comment by giansalex** [comment]
Ese parece ser el problema, este proyecto ahora requiere como mínimo php 7.2, como se indica en el [README](https://github.com/giansalex/lycet/#requerimientos)

**Comment by Ajahuanex** [comment]
Pero porque en [http://petstore.swagger.io/?url=https://raw.githubusercontent.com/giansalex/lycet/master/public/swagger.yaml](url) tambien existe el mismo problema. posiblemente githubusercontent esté con una version de PHP menor a 7.2, Pero de todas maneras hablaré con mi proveedor de hosting para ver si me pueden actualizar el PHP.

**Comment by Ajahuanex** [comment]
Tenias razón @giansalex ,  recibí respuesta de mi host remoto  con una version de PHP 7.2.
![Screenshot_10](https://user-images.githubusercontent.com/2767765/58485324-6b93c780-8129-11e9-8b13-b630a8805ab9.png)
Aunque tardo como 10 segundos pero respuesta al fin.

**Comment by giansalex** [comment]
Bien!, esa respuesta es un problema común con el servicios de sunat. 😞

**Comment by Ajahuanex** [comment]
Estoy probando Lycet en su última version en un host remoto con un PHP 7.2 y  por ahora todo sobre ruedas. no me percate del README. algo tan elemental.... pero gracias @giansalex por tu paciencia.
