### ISSUE TITLE
Sin Token.

### ISSUE THREAD

**Issue by Ajahuanex** [giansalex/lycet#82]
Estimado @giansalex , he tenido problemas al consumir el servicio de Lycet con Angular. Hay manera que configurar Lycet sin TOKEN ?

**Comment by giansalex** [comment]
Hola @Ajahuanex, que problema te ha surgido.?

**Comment by Ajahuanex** [comment]
Me sale `net::ERR_ABORTED 400 (Bad Request)` , también probé con NodeJS, con el código que me da postman para nodejs nativo y no sale ningún mensaje. Por otro lado en PHP no tengo problemas.
![Screenshot_11](https://user-images.githubusercontent.com/2767765/58560536-f2f53f80-81ea-11e9-9425-6e2fd95f6f36.png)

**Comment by giansalex** [comment]
El problema no es el token, es CORS y en #81 , te habia mencionado que eso solo ocurren en los navegadores. Tienes que agregar el dominio en `.env` o configurarlo a `CORS_ALLOW_ORIGIN=. `, para permitir cualquier dominio.
Por otro lado, esos headers que envías en angular, son innecesarios, esos headers son enviados desde el servidor, no al revés.

**Comment by Ajahuanex** [comment]
CORS_ALLOW_ORIGIN=.  Esta de esa manera. también probé con NodeJs. usando el codigo que quenera Postman. y sale la respuesta Undefined.
![Screenshot_12](https://user-images.githubusercontent.com/2767765/58563981-b8db6c00-81f1-11e9-8609-93146a533cf8.png)

**Comment by Ajahuanex** [comment]
Este es el código que use Para NodeJS.

`var request = require("request");

var options = { method: 'POST',
  url: 'http://www.megadatum.com/apis/lycet/public/api/v1/invoice/send',
  qs: { token: '123456' },
  headers: 
   { 'cache-control': 'no-cache',
     Connection: 'keep-alive',
     'content-length': '1207',
     'accept-encoding': 'gzip, deflate',
     Host: 'www.megadatum.com',
     'Postman-Token': '76852624-161a-4a3c-90d0-a6bc3258b41e,a511d3c3-002a-4ce9-9471-e86d8ce2fb52',
     'Cache-Control': 'no-cache',
     Accept: '*/*',
     'User-Agent': 'PostmanRuntime/7.13.0',
     token: '123456',
     'Content-Type': 'application/json' },
  body: 
   { tipoDoc: '01',
     serie: 'F008',
     correlativo: '111',
     fechaEmision: '2018-01-20T12:34:00+01:00',
     client: { tipoDoc: '6', numDoc: '20546687668', rznSocial: 'COMPANY SAC' },
     company: 
      { ruc: '20123456789',
        razonSocial: 'LYCET COMPANY SAC',
        nombreComercial: 'COMPANY ',
        address: 
         { ubigueo: '150101',
           codigoPais: 'PE',
           departamento: 'LIMA',
           provincia: 'LIMA',
           distrito: 'LIMA',
           urbanizacion: '-',
           direccion: 'AV ITALIA' } },
     tipoMoneda: 'PEN',
     mtoOperGravadas: 100,
     mtoOperInafectas: 0,
     mtoOperExoneradas: 0,
     mtoIGV: 18,
     mtoImpVenta: 118,
     details: 
      [ { unidad: 'NIU',
          cantidad: 12,
          codProducto: 'string',
          descripcion: 'PRODUCTO 1',
          mtoValorUnitario: 100,
          igv: 18,
          tipAfeIgv: '10',
          mtoPrecioUnitario: 118,
          mtoValorVenta: 100 } ],
     legends: [ { code: '1000', value: 'SON CIEN CON 00/100 SOLES' } ] },
  json: true };

 
const re = request(options, function (error, response, body) {
  if (error) throw new Error(error);
  console.log(body)
});

console.error('error:', re.error); // Print the error if one occurred
console.log('statusCode:', re.response && re.response.statusCode); // Print the response status code if a response was received
console.log('body:', re.body); // Print the HTML for the Google homepage.`

**Comment by Ajahuanex** [comment]
Mi idea es utilizar NodeJs como Bakend para administrar la base de datos y algunas APIS externas para el sistema de facturación. Donde la administracion de acceso estaría acargo de NodeJS, es por ese motivo que mi pregunta era si ¿hay alguna manera de configurar Lycet que no use Token?.
![project](https://user-images.githubusercontent.com/2767765/58564502-ae6da200-81f2-11e9-8fd7-a07b5a224aa5.jpg)

**Comment by giansalex** [comment]
Y porque consideras que el problema es el token

**Comment by Ajahuanex** [comment]
Porque ya probe otras APIS que no usaban autenticación, y no tuve problemas en consumir sus servicios con Nodejs  y tampoco con Angular.

**Comment by Ajahuanex** [comment]
Gracias, de todos modos, por fin recibí respuesta en NodeJs con esta librería `node-rest-client`.
![Screenshot_13](https://user-images.githubusercontent.com/2767765/58571081-b3d0e980-81fe-11e9-9997-1c55ec27e106.png)

**Comment by giansalex** [comment]
Eso indica que probablemente el problema era al realizar la llamada.

**Comment by Ajahuanex** [comment]
Como siempre @giansalex  tenías razón, quite los campos de cabecera innecesaria en Angular. y todo va bien..... Voy a aprender symfony 4 o flex  para aportar con  esta Lycet, tienes algún libro  que me recomiendes o tutoriales que tu consideres buenos?, Gracias de antemano, saludos.

![Screenshot_14](https://user-images.githubusercontent.com/2767765/58583353-6f9f1280-8219-11e9-9367-5e4930f04733.png)

**Comment by giansalex** [comment]
@Ajahuanex , a mi me ha servido mucha la [documentacion oficial](https://symfony.com/doc/current/setup.html), alli tambien tienes guias para los diferentes componentes de symfony
