### ISSUE TITLE
PDF en host remoto

### ISSUE THREAD

**Issue by Ajahuanex** [giansalex/lycet#93]
Hola @giansalex  descargue el ejcutable para linux de [https://github.com/h4cc/wkhtmltopdf-amd64](url) luego puse la ruta donde guarde en la carpeta `bin/ ` donde esta Lycet. Después añadí la ruta, sin embargo no me genera el PDF.
 `WKHTMLTOPDF_PATH=/bin/wkhtmltopdf-amd64`

![Screenshot_15](https://user-images.githubusercontent.com/2767765/58648684-dbdc4d80-82cf-11e9-8a64-1d933a0cfd5c.png)
 mi proveedor de hosting tiene Linux x86_64

**Comment by giansalex** [comment]
En `WKHTMLTOPDF_PATH`  deberías colocar la ruta completa de la ubicación del ejecutable

**Comment by Ajahuanex** [comment]
ya puse `WKHTMLTOPDF_PATH= http://www.megadatum.com/apis/lycet/bin/wkhtmltopdf-amd64`  el tipo de error cambio a fetch.
![Screenshot_16](https://user-images.githubusercontent.com/2767765/58651471-07166b00-82d7-11e9-9bd8-033956bd908b.png)

**Comment by giansalex** [comment]
WKHTMLTOPDF_PATH se refiere a la ruta de archivos completa, es imposible que lea una URL.
Ejm: `WKHTMLTOPDF_PATH=/home/userxx/htdocs/bin/wkhtmltopdf-amd64`,

**Comment by Ajahuanex** [comment]
`WKHTMLTOPDF_PATH=/home/megadat1/public_html/apis/lycet/bin/wkhtmltopdf-amd64` esa es la ruta que me da el servidor, pero persiste el problema con error del tipo 500

**Comment by Ajahuanex** [comment]
en postman me sale mas detalles del error.
![Screenshot_17](https://user-images.githubusercontent.com/2767765/58653474-670f1080-82db-11e9-9314-7894dbcbdc4e.png)

**Comment by giansalex** [comment]
Dirigete a `disable_functions=` en php.ini y quita esa función.
Tambien dar permiso de ejecucion al ejecutable de wkhtmltopdf

**Comment by Ajahuanex** [comment]
eso va ser complicado, por las políticas de seguridad del hosting, tengo acceso para modificar pocas opciones ,
![Screenshot_19](https://user-images.githubusercontent.com/2767765/58665178-e7db0600-82f5-11e9-8bf7-0555077f6f11.png)
`disable_functions=` esta de la siguiente manera.
![Screenshot_18](https://user-images.githubusercontent.com/2767765/58665222-04773e00-82f6-11e9-98b0-a8aca2a2ce46.png)

**Comment by Ajahuanex** [comment]
@giansalex, que otras alternativas habría para no modificar php.ini, ... Nose, quiza usar la librería `Dompdf`?,

**Comment by giansalex** [comment]
Uno de los [requerimientos](https://github.com/giansalex/greenter-htmltopdf#requirements) para usar greenter-report, es tener activada la funcion `exec()`.
En los hosting creo que puedes indicar la ruta del php.ini en el htacces usando esta [configuracion](https://support.hostgator.com/articles/specialized-help/technical/how-to-get-your-php-ini-path-with-suphp) .

Si quieres usar otra libreria para generar el pdf, puedes hacerlo haciendo tu propia implementacion y configurarlo en [servicios](https://github.com/giansalex/lycet/blob/a1bb05656d448dfd244028a20bb0641b4b55bd33/config/services.yaml#L60)

**Comment by Ajahuanex** [comment]
> Uno de los [requerimientos](https://github.com/giansalex/greenter-htmltopdf#requirements) para usar greenter-report, es tener activada la funcion `exec()`.
> En los hosting creo que puedes indicar la ruta del php.ini en el htacces usando esta [configuracion](https://support.hostgator.com/articles/specialized-help/technical/how-to-get-your-php-ini-path-with-suphp) .
> 
> Si quieres usar otra libreria para generar el pdf, puedes hacerlo haciendo tu propia implementacion y configurarlo en [servicios](https://github.com/giansalex/lycet/blob/a1bb05656d448dfd244028a20bb0641b4b55bd33/config/services.yaml#L60)

Estoy utilizando la librería [mpdf](https://mpdf.github.io/) y me funcionó en un host remoto, mi duda es si mi solución es válida. 

1. Agrego una variable de entorno `MDPF=1` en `.env` para elegir entre wkhtmltopdf  ó mpdf.
2. Agrego código al archivo `..\lycet\vendor\greenter\htmltopdf\src\Report\PdfReport.php` para utilizar la libreria `mpdf`.
![ly](https://user-images.githubusercontent.com/2767765/58973350-5d772400-8785-11e9-908f-65eca9b51050.jpg)

Efectivamente genero un pdf,... claro que me falta aún completar las configuraciones de la librería mpdf, que no reconoce algunos  propiedades css de la plantilla, 
![Screenshot_26](https://user-images.githubusercontent.com/2767765/58973668-1fc6cb00-8786-11e9-8da0-4ea5b67be160.png)
![Screenshot_27](https://user-images.githubusercontent.com/2767765/58973771-67e5ed80-8786-11e9-970b-5872f7e6d1ad.png)

**Comment by giansalex** [comment]
No, deberias crear tu propia clase, `PdfReport` esta pensado para usar `wkhtmltopdf`.

**Comment by giansalex** [comment]
El principal motivo por el que use `wkhtmltopdf`, en lugar de librerias existentes en PHP, es por que no soportan paginas html modernas, y puedes notarlo usando mpdf, el resultado no es el mismo que usando wkhtmltopdf

**Comment by Ajahuanex** [comment]
Ya cree mi propia clase `MpdfReport ` y le puse el alias en `services.yaml.`
![Screenshot_28](https://user-images.githubusercontent.com/2767765/58977790-06c31780-8790-11e9-9d53-be4ff990383c.png),

**Comment by Ajahuanex** [comment]
> El principal motivo por el que use `wkhtmltopdf`, en lugar de librerias existentes en PHP, es por que no soportan paginas html modernas, y puedes notarlo usando mpdf, el resultado no es el mismo que usando wkhtmltopdf

Si, tienes razón, usando la librería mpdf voy a tener que modificar el css de las plantillas de twig para que se vea algo decente mis PDFs,

**Comment by Ajahuanex** [comment]
Sin embargo, yo pienso que la API `Lycet` debería de hacer un switch a una liberia alternativa para renderizar los PDFs, ya que al colocarlos en producción en un host remoto(generalmente NO están activas las funciones Exec()).

**Comment by giansalex** [comment]
Si, hay muchas cosas que se pueden hacer, tambien habia una sugerencia para crear la impresion para Ticket, directamente con código PHP, usando por ejemplo FPDF
