### ISSUE TITLE
convertir de UBL a JSON

### ISSUE THREAD

**Issue by CesarNicolini** [giansalex/lycet#94]
Hola ... una consulta estoy haciendo una aplicación que lea las boletas de la sunat para almacenarlas en DDBB. El problema que no existe ningún programa que transforme de UBL a JSON para poder leer la información del documento XML. ME podrías dar una mano, por favor?

**Comment by giansalex** [comment]
Hola @CesarNicolini, eso no esta muy relacionado con el UBL, lo que tendrías que buscar es un programa para convertir xml a json

**Comment by giansalex** [comment]
Tal vez esto te pueda servir, convierte el xml en una entidad de PHP, de alli podrias serializarlo a json
https://github.com/giansalex/greenter-xml-parser
