### ISSUE TITLE
PDF salto de página,

### ISSUE THREAD

**Issue by Ajahuanex** [giansalex/lycet#96]
Mi duda es , si al tener muchos items en el detalle de la factura, y éste ocupa mas de 2 hojas en el pdf que se genera. ¿ Es necesario que en cada hoja vayan los datos obligatorios?(RUC, razon social,...etc). o puede estar de la siguiente manera.
![Screenshot_29](https://user-images.githubusercontent.com/2767765/59058273-e2d00680-8861-11e9-881f-ba39829dc896.png)

**Comment by giansalex** [comment]
Eso deberia manejarse como las facturas fisicas.

**Comment by Ajahuanex** [comment]
En todo caso,las plantillas `twig` deberían de modificarse para poner un limite de items por hoja.

**Comment by giansalex** [comment]
la cantidad de items se especifica en la variable `setDetails()`, alli podrias limitar la cantidad de items que se visualiza.
