### ISSUE TITLE
No se muestra el Hash en el PDF

### ISSUE THREAD

**Issue by OD-n** [giansalex/lycet#97]
Que se tendría que hacer para que no se muestre el hash en el pdf generado?
Encontré el codigo siguiente:
`$parameters = [
            'system' => [
                'logo' => $logo,
//                'hash' => '',
            ],
            'user' => [
                'resolucion' => '-',
                'header' => '',
            ]
        ];`

Ahi está comentado el hash; si coloco cualquier texto ahí, aparece en la factura, lo que quiero saber es por qué esta comentado y que debo hacer para poder hacer conseguirlo.

**Comment by giansalex** [comment]
Hola, eso seria para enviarlo como parámetro, se puede obtener apartir del xml, con [este codigo](https://github.com/giansalex/greenter-sample/blob/64d75b9a00c76efbfbbf09180ffaff65f27d2546/src/Util.php#L208)

**Comment by giansalex** [comment]
Relacionado a agregar información extra al reporte. #105

**Comment by OD-n** [comment]
Por si alguno se topó con ello, generé el HASH cambiando en el archivo src->service->DocumentRequest.php

    public function pdf(): Response
    {
        $document = $this->getDocument();

        $logo = $this->getParameter('logo');

        $see = $this->getSee();//Esta es la primera linea

        $xml  = $see->getXmlSigned($document);//Esta es la segunda linea

        $parameters = [
            'system' => [
                'logo' => $logo,
                'hash' => $this->GetHashFromXml($xml), //Esta es la tercera linea
            ],
            'user' => [
                'resolucion' => '-',
                'header' => '',
            ]
        ];

        $report = $this->getReport();
        $pdf = $report->render($document, $parameters);
        if ($pdf === false) {
            $message = $this->tryGetError($report);

            return $this->json(['message' => $message], 500);
        }

        return $this->file($pdf, $document->getName().'.pdf', 'application/pdf');
    }
